// Catalogue des équipements Ypocamp (accessoires posés en interne, hors options usine).
// Source : Tarif_cessions_Equipements_ODOO2026_A_jour_0108.xlsx, onglet SALONS.
// achatHt = colonne B (cession HT posé) | poseVentileeHt = colonne I (pose ventilée HT) | prixTtc = colonne R (PVTTC posé)
const EQUIPEMENTS_YPOCAMP = [
  { categorie: "Audiovisuel", sousCategorie: "ANTENNE", designation: "Antenne TELEPLUS + Mat 3G", achatHt: 340.48, poseVentileeHt: 175.0, prixTtc: 684.0 },
  { categorie: "Audiovisuel", sousCategorie: "ANTENNE", designation: "Antenne OMNI TELECO WING ou équivalent", achatHt: 431.8, poseVentileeHt: 175.0, prixTtc: 590.0 },
  { categorie: "Audiovisuel", sousCategorie: "ANTENNE", designation: "Sat Auto 60 OTO SAT Twin 1 seul démo de livré ou équivalent", achatHt: 1185.4, poseVentileeHt: 250.0, prixTtc: 2148.0 },
  { categorie: "Audiovisuel", sousCategorie: "ANTENNE", designation: "Sat Auto 85 OTO SAT Twin 1 seul démo de livré ou équivalent", achatHt: 1609.6, poseVentileeHt: 250.0, prixTtc: 2745.0 },
  { categorie: "Audiovisuel", sousCategorie: "TELEVISEURS", designation: "Supplément 2ème TV en regardant des programmes differents (Prendre comme base la prix de l'Antenne TWIN et ajouter ce forfait (1 TV+ DEMO +SUPPORT+ cablage + prise + HDMI)", achatHt: 543.48, poseVentileeHt: 150.0, prixTtc: 980.0 },
  { categorie: "Audiovisuel", sousCategorie: "TELEVISEURS", designation: "TV 19 pouces GOOGLE TV", achatHt: 254.0, poseVentileeHt: 50.0, prixTtc: 419.0 },
  { categorie: "Audiovisuel", sousCategorie: "TELEVISEURS", designation: "TV 22 pouces GOOGLE TV", achatHt: 266.0, poseVentileeHt: 50.0, prixTtc: 479.0 },
  { categorie: "Audiovisuel", sousCategorie: "TELEVISEURS", designation: "TV 32 pouces GOOGLE TV", achatHt: 338.0, poseVentileeHt: 50.0, prixTtc: 599.0 },
  { categorie: "Audiovisuel", sousCategorie: "TELEVISEURS", designation: "SUPPORT TV COULISSANT LATERAL", achatHt: 170.0, poseVentileeHt: 50.0, prixTtc: 409.0 },
  { categorie: "Audiovisuel", sousCategorie: "GPS", designation: "MULTIMEDIA CARPLAY ET ANDROID AUTO AVEC CAMERA ALPINE 611", achatHt: 1022.8, poseVentileeHt: 250.0, prixTtc: 1768.0 },
  { categorie: "Energie", sousCategorie: "BATTERIES", designation: "1ère Batterie cellule GEL 105 Ah", achatHt: 224.0, poseVentileeHt: 50.0, prixTtc: 378.0 },
  { categorie: "Energie", sousCategorie: "BATTERIES", designation: "2ème Batterie cellule GEL 105 Ah (Spécifique pour un véhicule HORS TRIGANO) avec Frigo à compression (Avec cosses de protection, cables, fixation, porte-fusible)", achatHt: 268.0, poseVentileeHt: 100.0, prixTtc: 549.0 },
  { categorie: "Energie", sousCategorie: "PANNEAU SOLAIRE", designation: "PANNEAU SOLAIRE 140 WATTS 127,8cmx58,5 cm", achatHt: 266.4, poseVentileeHt: 150.0, prixTtc: 685.0 },
  { categorie: "Energie", sousCategorie: "PANNEAU SOLAIRE", designation: "PANNEAU SOLAIRE SOUPLE 135 Watts (Spécial Toit Relevable) 109X102", achatHt: 324.0, poseVentileeHt: 150.0, prixTtc: 779.0 },
  { categorie: "Energie", sousCategorie: "PANNEAU SOLAIRE", designation: "PANNEAU SOLAIRE 170 WATTS BLACK BOOSTER + 35% 146,5 X 54 cm", achatHt: 342.0, poseVentileeHt: 150.0, prixTtc: 979.0 },
  { categorie: "Energie", sousCategorie: "PRISE ELECTRIQUE SUPPLEMENTAIRE", designation: "PRISE SUPPLEMENTAIRE 12 V / 220 V / USB / ANT", achatHt: 118.0, poseVentileeHt: 100.0, prixTtc: 268.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F 80 / avancée 2m50 FOURGON", designation: "Store F 80 3,40 M + 1 KIT FIAMMA ou équivalent Fourgon de 5,40 M", achatHt: 878.08, poseVentileeHt: 100.0, prixTtc: 1459.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F 80 / avancée 2m50 FOURGON", designation: "Store F 80 3,7 0M + 1 KIT FIAMMA ou équivalent Fourgon de 6,00 M", achatHt: 1000.0, poseVentileeHt: 100.0, prixTtc: 1591.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F 80 / avancée 2m50 FOURGON", designation: "Store F 80 4 M + 2 KITS FIAMMA ou équivalent Fourgon de 6,36 M", achatHt: 967.6, poseVentileeHt: 100.0, prixTtc: 1757.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F 80 / avancée 2m50 FOURGON", designation: "OPTION TITANIUM TTE CATEGORIE", achatHt: 60.0, poseVentileeHt: 0.0, prixTtc: 200.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE THULE 9002 / avancée 2m50 (CARTHAGO / RAPIDO DISTINCTION)", designation: "Store 9002 4,5 M THULE SANS KIT POSE", achatHt: 1804.8, poseVentileeHt: 150.0, prixTtc: 2617.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE THULE 9002 / avancée 2m50 (CARTHAGO / RAPIDO DISTINCTION)", designation: "Store 9002 5 M THULE SANS KIT POSE", achatHt: 1968.0, poseVentileeHt: 150.0, prixTtc: 2760.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE THULE 9002 / avancée 2m50 (CARTHAGO / RAPIDO DISTINCTION)", designation: "Store 9002 5,5 M THULE SANS KIT POSE", achatHt: 2230.8, poseVentileeHt: 150.0, prixTtc: 2960.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE VAN", designation: "KIT Supports et store F35 CAMPEREVE/ STYLEVAN FORD", achatHt: 720.0, poseVentileeHt: 150.0, prixTtc: 1049.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE VAN", designation: "KIT Supports et store STYLEVAN / VW", achatHt: 720.0, poseVentileeHt: 150.0, prixTtc: 1049.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE VAN", designation: "KIT supports seul posé RAPIDO serie Compact - jusqu’à 4m50", achatHt: 380.0, poseVentileeHt: 150.0, prixTtc: 490.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F45S / avancée (Carthago/Rapido distinction)", designation: "STORE FIAMMA F 45 S 3,5 M+ 1 KIT FIAMMA ou équivalent", achatHt: 866.8, poseVentileeHt: 100.0, prixTtc: 1530.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F45S / avancée (Carthago/Rapido distinction)", designation: "STORE FIAMMA F 45 S 4 M+ 1 KIT FIAMMA ou équivalent", achatHt: 941.2, poseVentileeHt: 100.0, prixTtc: 1681.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F45S / avancée (Carthago/Rapido distinction)", designation: "STORE FIAMMA F 45 S 4,5 M+ 1 KIT FIAMMA ou équivalent", achatHt: 1045.6, poseVentileeHt: 100.0, prixTtc: 1826.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F45S / avancée (Carthago/Rapido distinction)", designation: "STORE FIAMMA F 45 S 5 M+ 1 KIT FIAMMA ou équivalent", achatHt: 1498.0, poseVentileeHt: 100.0, prixTtc: 2316.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "STORE FIAMMA F45S / avancée (Carthago/Rapido distinction)", designation: "OPTION TITANIUM TTE CATEGORIE", achatHt: 504.0, poseVentileeHt: 0.0, prixTtc: 685.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT CARAVANE", designation: "AUVENT CARAVANE 2,50 M ATLANTIQUE TRIGANO taille E", achatHt: 938.0, poseVentileeHt: 0.0, prixTtc: 1351.2 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT CARAVANE", designation: "AUVENT CARAVANE 2,50 M ATLANTIQUE TRIGANO taille F", achatHt: 955.0, poseVentileeHt: 0.0, prixTtc: 1378.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT CARAVANE", designation: "AUVENT CARAVANE 2,50 M ATLANTIQUE TRIGANO taille G", achatHt: 976.0, poseVentileeHt: 0.0, prixTtc: 1406.4 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT CARAVANE", designation: "AUVENT CARAVANE 2,50 M ATLANTIQUE TRIGANO taille H", achatHt: 992.0, poseVentileeHt: 0.0, prixTtc: 1428.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT CARAVANE", designation: "AUVENT CARAVANE 2,50 M ATLANTIQUE TRIGANO taille I", achatHt: 1067.0, poseVentileeHt: 0.0, prixTtc: 1534.8 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT CARAVANE", designation: "AUVENT CARAVANE 2,50 M ATLANTIQUE TRIGANO taille J", achatHt: 1091.0, poseVentileeHt: 0.0, prixTtc: 1569.6 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT GONFLABLE CARAVANE", designation: "AUVENT Gonflable CARAVANE LIMA 300", achatHt: 907.0, poseVentileeHt: 0.0, prixTtc: 1235.0 },
  { categorie: "Stores Exterieurs", sousCategorie: "AUVENT GONFLABLE CARAVANE", designation: "AUVENT Gonflable CARAVANE LIMA 400", achatHt: 1098.0, poseVentileeHt: 0.0, prixTtc: 1567.0 },
  { categorie: "Portage", sousCategorie: "ATTELAGE FOURGONS / VANS", designation: "Attelage fourgon Fiat ducato / peugeot boxer", achatHt: 591.2, poseVentileeHt: 200.0, prixTtc: 1048.0 },
  { categorie: "Portage", sousCategorie: "ATTELAGE FOURGONS / VANS", designation: "Attelage fourgon Ford custom", achatHt: 681.2, poseVentileeHt: 200.0, prixTtc: 1100.0 },
  { categorie: "Portage", sousCategorie: "ATTELAGE FOURGONS / VANS", designation: "Attelage fourgon Peugeot expert /", achatHt: 729.2, poseVentileeHt: 200.0, prixTtc: 1334.0 },
  { categorie: "Portage", sousCategorie: "PORTE VELO", designation: "Porte Vélo 2 PRO OU PRO C FIAMMA ou équivalent", achatHt: 337.6, poseVentileeHt: 100.0, prixTtc: 642.0 },
  { categorie: "Portage", sousCategorie: "PORTE VELO", designation: "Porte Vélo 3 FIAMMA ou équivalent", achatHt: 385.6, poseVentileeHt: 100.0, prixTtc: 738.0 },
  { categorie: "Portage", sousCategorie: "PORTE VELO", designation: "Option 4eme Vélo", achatHt: 50.0, poseVentileeHt: 12.5, prixTtc: 142.25 },
  { categorie: "Portage", sousCategorie: "PORTE VELO", designation: "Porte vélo ascensionnel manuel fiamma LIFT ou équivalent", achatHt: 762.0, poseVentileeHt: 150.0, prixTtc: 1299.0 },
  { categorie: "Portage", sousCategorie: "PORTE VELO", designation: "Porte Vélo FIAMMA 200 DJ FOURGON FIAT 35 KGS MAX", achatHt: 535.2, poseVentileeHt: 150.0, prixTtc: 829.0 },
];

module.exports = { EQUIPEMENTS_YPOCAMP };