// Données de référence extraites des tarifs distributeur/public 2027 (Dreamer + Rapido),
// reprises telles quelles depuis le prototype validé. Ce fichier est la source de vérité
// pour le script d'import scripts/seed.js — ne pas modifier sans mettre à jour les deux en parallèle.

function zipCompat(ids, statuts) {
  const map = {};
  ids.forEach((id, i) => { map[id] = statuts[i]; });
  return map;
}

// ---------------------------------------------------------------------------
// VÉHICULES
// ---------------------------------------------------------------------------

const DREAMER_VEHICULE_IDS = ["d43", "d43p", "d43up", "d43upp", "d55", "d55p", "d55up", "d55upp", "d68", "d68p", "d68up", "d68upp", "cf", "cfp", "cs", "csp"];

const DREAMER_VEHICULES = [
  { id: "d43", nom: "D43 FUN 120cv", prixUsineHt: 39803.67, prixPublicTtc: 54500 },
  { id: "d43p", nom: "D43 FUN+ 140cv", prixUsineHt: 43763.67, prixPublicTtc: 59900 },
  { id: "d43up", nom: "D43 UP FUN 120cv", prixUsineHt: 44203.67, prixPublicTtc: 60500 },
  { id: "d43upp", nom: "D43 UP FUN+ 140cv", prixUsineHt: 48163.67, prixPublicTtc: 65900 },
  { id: "d55", nom: "D55 FUN 140cv", prixUsineHt: 43030.33, prixPublicTtc: 58900 },
  { id: "d55p", nom: "D55 FUN+ 140cv", prixUsineHt: 45963.67, prixPublicTtc: 62900 },
  { id: "d55up", nom: "D55 UP FUN 140cv", prixUsineHt: 47430.33, prixPublicTtc: 64900 },
  { id: "d55upp", nom: "D55 UP FUN+ 140cv", prixUsineHt: 50363.67, prixPublicTtc: 68900 },
  { id: "d68", nom: "D68 FUN 140cv", prixUsineHt: 44497.0, prixPublicTtc: 60900 },
  { id: "d68p", nom: "D68 FUN+ 140cv", prixUsineHt: 47430.33, prixPublicTtc: 64900 },
  { id: "d68up", nom: "D68 UP FUN 140cv", prixUsineHt: 48897.0, prixPublicTtc: 66900 },
  { id: "d68upp", nom: "D68 UP FUN+ 140cv", prixUsineHt: 51097.0, prixPublicTtc: 69900 },
  { id: "cf", nom: "CAMPER FIVE FUN 140cv", prixUsineHt: 46403.67, prixPublicTtc: 63500 },
  { id: "cfp", nom: "CAMPER FIVE FUN+ 140cv", prixUsineHt: 49337.0, prixPublicTtc: 67500 },
  { id: "cs", nom: "CAMPER SPORT FUN 140cv", prixUsineHt: 46403.67, prixPublicTtc: 63500 },
  { id: "csp", nom: "CAMPER SPORT FUN+ 140cv", prixUsineHt: 49337.0, prixPublicTtc: 67500 },
].map((v) => ({ ...v, marque: "Dreamer", gamme: "FUN", type: "CAMPING_CAR", typeCarrosserie: "FOURGON", collection: 2027 }));

const RAPIDO_VEHICULE_IDS = ["r_c03", "r_c50", "r_c55", "r_c66ol", "r_c86ol", "r_606f", "r_666fol", "r_686f", "r_696fol"];

const RAPIDO_VEHICULES = [
  { id: "r_c03", nom: "C03", prixUsineHt: 53124.10, prixPublicTtc: 73500 },
  { id: "r_c50", nom: "C50", prixUsineHt: 54574.10, prixPublicTtc: 75500 },
  { id: "r_c55", nom: "C55", prixUsineHt: 54574.10, prixPublicTtc: 75500 },
  { id: "r_c66ol", nom: "C66 Optimum Line", prixUsineHt: 59141.60, prixPublicTtc: 81800 },
  { id: "r_c86ol", nom: "C86 Optimum Line", prixUsineHt: 59141.60, prixPublicTtc: 81800 },
  { id: "r_606f", nom: "606F", prixUsineHt: 54864.10, prixPublicTtc: 75900 },
  { id: "r_666fol", nom: "666F Optimum Line", prixUsineHt: 60591.60, prixPublicTtc: 83800 },
  { id: "r_686f", nom: "686F", prixUsineHt: 55516.60, prixPublicTtc: 76800 },
  { id: "r_696fol", nom: "696F Optimum Line", prixUsineHt: 60591.60, prixPublicTtc: 83800 },
].map((v) => ({ ...v, marque: "Rapido", gamme: "Profilés (Séries C / 6F)", type: "CAMPING_CAR", typeCarrosserie: "PROFILE", collection: 2027 }));

const RAPIDO_INTEGRAUX_IDS = ["r_c55i", "r_c66iol", "r_c86iol", "r_850f", "r_866fol", "r_896fol", "r_8066dfalko", "r_8086dfalko", "r_8096dfalko", "r_i66mtruma", "r_i66malde", "r_i96mtruma", "r_i96malde", "r_i166malde", "r_i196malde"];

const RAPIDO_VEHICULES_INTEGRAUX = [
  { id: "r_c55i", nom: "C55I", prixUsineHt: 61389.10, prixPublicTtc: 84900 },
  { id: "r_c66iol", nom: "C66I Optimum Line", prixUsineHt: 66464.10, prixPublicTtc: 91900 },
  { id: "r_c86iol", nom: "C86I Optimum Line", prixUsineHt: 66464.10, prixPublicTtc: 91900 },
  { id: "r_850f", nom: "850F", prixUsineHt: 62114.10, prixPublicTtc: 85900 },
  { id: "r_866fol", nom: "866F Optimum Line", prixUsineHt: 67914.10, prixPublicTtc: 93900 },
  { id: "r_896fol", nom: "896F Optimum Line", prixUsineHt: 67914.10, prixPublicTtc: 93900 },
  { id: "r_8086dfalko", nom: "8086dF AL-KO", prixUsineHt: 70524.10, prixPublicTtc: 97500 },
  { id: "r_8066dfalko", nom: "8066dF AL-KO", prixUsineHt: 71974.10, prixPublicTtc: 99500 },
  { id: "r_8096dfalko", nom: "8096dF AL-KO", prixUsineHt: 71974.10, prixPublicTtc: 99500 },
  { id: "r_i66mtruma", nom: "I66M TRUMA (Mercedes)", prixUsineHt: 99391.47, prixPublicTtc: 138900 },
  { id: "r_i96mtruma", nom: "I96M TRUMA (Mercedes)", prixUsineHt: 99391.47, prixPublicTtc: 138900 },
  { id: "r_i66malde", nom: "I66M ALDE (Mercedes)", prixUsineHt: 102258.13, prixPublicTtc: 142900 },
  { id: "r_i96malde", nom: "I96M ALDE (Mercedes)", prixUsineHt: 102258.13, prixPublicTtc: 142900 },
  { id: "r_i166malde", nom: "I166M ALDE (Mercedes)", prixUsineHt: 115158.13, prixPublicTtc: 160900 },
  { id: "r_i196malde", nom: "I196M ALDE (Mercedes)", prixUsineHt: 115158.13, prixPublicTtc: 160900 },
].map((v) => ({ ...v, marque: "Rapido", gamme: "Intégraux (Séries C / 8F / 80dF / Distinction)", type: "CAMPING_CAR", typeCarrosserie: "INTEGRAL", collection: 2027 }));

const RAPIDO_VANS_IDS = ["r_v55ol", "r_v62ol", "r_v64", "r_v65xl", "r_v68"];

const RAPIDO_VEHICULES_VANS = [
  { id: "r_v55ol", nom: "V55 Optimum Line", prixUsineHt: 52553.40, prixPublicTtc: 71900 },
  { id: "r_v68", nom: "V68", prixUsineHt: 48886.73, prixPublicTtc: 66900 },
  { id: "r_v62ol", nom: "V62 Optimum Line", prixUsineHt: 54020.07, prixPublicTtc: 73900 },
  { id: "r_v64", nom: "V64", prixUsineHt: 50353.40, prixPublicTtc: 68900 },
  { id: "r_v65xl", nom: "V65 XL", prixUsineHt: 51086.73, prixPublicTtc: 69900 },
].map((v) => ({ ...v, marque: "Rapido", gamme: "Vans (Fourgons)", type: "CAMPING_CAR", typeCarrosserie: "FOURGON", collection: 2027 }));

// Source : Tarifs_HT_Camping-cars.pdf / Tarifs_public_Camping-cars.pdf — Adria, collection 2027 (tarif au 01/07/2026)
const ADRIA_VEHICULES_CC = [
  { id: "adria_compact_dc_citroen", nom: "Profilé COMPACT DC (Citroën Jumper Select)", prixUsineHt: 53763, prixPublicTtc: 75900 },
  { id: "adria_compact_dl_citroen", nom: "Profilé COMPACT DL (Citroën Jumper Select)", prixUsineHt: 53054, prixPublicTtc: 74900 },
  { id: "adria_compact_dl_fiat_supreme", nom: "Profilé COMPACT DL (Fiat Ducato Supreme)", prixUsineHt: 59429, prixPublicTtc: 83900 },
  { id: "adria_matrix_650dl_citroen", nom: "Profilé MATRIX 650 DL (Citroën Jumper Select)", prixUsineHt: 55604, prixPublicTtc: 78500 },
  { id: "adria_matrix_670dc_citroen", nom: "Profilé MATRIX 670 DC (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_matrix_670dl_citroen", nom: "Profilé MATRIX 670 DL (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_matrix_670dc_fiat_supreme", nom: "Profilé MATRIX 670 DC (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_matrix_670dl_fiat_supreme", nom: "Profilé MATRIX 670 DL (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_coral_670dc_citroen", nom: "Profilé CORAL 670 DC (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_coral_670dl_citroen", nom: "Profilé CORAL 670 DL (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_coral_670dc_fiat_supreme", nom: "Profilé CORAL 670 DC (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_coral_670dl_fiat_supreme", nom: "Profilé CORAL 670 DL (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_coralxl_650dk_citroen", nom: "Capucine CORAL XL 650 DK (Citroën Jumper Select)", prixUsineHt: 55179, prixPublicTtc: 77900 },
  { id: "adria_coralxl_660sl_citroen", nom: "Capucine CORAL XL 660 SL (Citroën Jumper Select)", prixUsineHt: 55888, prixPublicTtc: 78900 },
  { id: "adria_sonic_700dc_fiat_select", nom: "Intégral SONIC 700 DC (Fiat Ducato Select, 140cv MAN.)", prixUsineHt: 70472, prixPublicTtc: 99490 },
  { id: "adria_sonic_700dl_fiat_select", nom: "Intégral SONIC 700 DL (Fiat Ducato Select, 140cv MAN.)", prixUsineHt: 70472, prixPublicTtc: 99490 },
  { id: "adria_sonic_700dl_fiat_supreme", nom: "Intégral SONIC 700 DL (Fiat Ducato Supreme, 44H 160cv AUT.)", prixUsineHt: 82096, prixPublicTtc: 115900 },
  { id: "adria_sonic_700dc_fiat_supreme", nom: "Intégral SONIC 700 DC (Fiat Ducato Supreme, 44H 160cv AUT.)", prixUsineHt: 82096, prixPublicTtc: 115900 },
  { id: "adria_supersonic_780dc", nom: "Intégral SUPERSONIC 780 DC (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 116804, prixPublicTtc: 164900 },
  { id: "adria_supersonic_780dl", nom: "Intégral SUPERSONIC 780 DL (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 116804, prixPublicTtc: 164900 },
  { id: "adria_supersonic_780sl", nom: "Intégral SUPERSONIC 780 SL (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 116804, prixPublicTtc: 164900 },
  { id: "adria_supersonic_890lc", nom: "Intégral SUPERSONIC 890 LC (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 124596, prixPublicTtc: 175900 },
  { id: "adria_supersonic_890ll", nom: "Intégral SUPERSONIC 890 LL (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 124596, prixPublicTtc: 175900 },
].map((v) => ({
  ...v,
  marque: "Adria",
  gamme: "Camping-cars",
  type: "CAMPING_CAR",
  typeCarrosserie: v.nom.startsWith("Intégral") ? "INTEGRAL" : v.nom.startsWith("Capucine") ? "CAPUCINE" : "PROFILE",
  collection: 2027,
}));

// Source : Tarifs_HT_Fourgons.pdf / Tarifs_public_Fourgons.pdf — Adria, collection 2027 (tarif au 01/07/2026)
const ADRIA_VEHICULES_FOURGONS = [
  { id: "adria_twin_540spb_citroen", nom: "TWIN 540 SPB — Gamme Select (Citroën Jumper, 35L 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 43846, prixPublicTtc: 61900 },
  { id: "adria_twin_600spb_citroen_ptr", nom: "TWIN 600 SPB PTR — Gamme Select (Citroën Jumper, 35L 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 45263, prixPublicTtc: 63900 },
  { id: "adria_twin_600spb_family_citroen", nom: "TWIN 600 SPB FAMILY — Gamme Select (Citroën Jumper, 35L 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 45971, prixPublicTtc: 64900 },
  { id: "adria_twin_640slb_citroen_ptr", nom: "TWIN 640 SLB PTR — Gamme Select (Citroën Jumper, 35H 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 46679, prixPublicTtc: 65900 },
  { id: "adria_twin_640sgx_citroen_ptr", nom: "TWIN 640 SGX PTR — Gamme Select (Citroën Jumper, 35H 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 48804, prixPublicTtc: 68900 },
  { id: "adria_twin_540spb_fiat_supreme_ptr", nom: "TWIN 540 SPB PTR — Gamme Supreme (Fiat Ducato, 35L 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 53763, prixPublicTtc: 75900 },
  { id: "adria_twin_600spb_fiat_supreme_ptr", nom: "TWIN 600 SPB PTR — Gamme Supreme (Fiat Ducato, 35L 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 50929, prixPublicTtc: 71900 },
  { id: "adria_twin_640spb_family_fiat_supreme", nom: "TWIN 640 SPB FAMILY — Gamme Supreme (Fiat Ducato, 35H 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 52346, prixPublicTtc: 73900 },
  { id: "adria_twin_640slb_fiat_supreme_ptr", nom: "TWIN 640 SLB PTR — Gamme Supreme (Fiat Ducato, 35H 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 52346, prixPublicTtc: 73900 },
  { id: "adria_twin_640sgx_fiat_supreme_ptr", nom: "TWIN 640 SGX PTR — Gamme Supreme (Fiat Ducato, 35H 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 54471, prixPublicTtc: 76900 },
  { id: "adria_supertwin_600spb_ptr", nom: "SUPERTWIN 600 SPB PTR — Gamme Supertwin (Mercedes, 4X4 190cv AUT.)", gammeTwin: "Supertwin", prixUsineHt: 105471, prixPublicTtc: 148900 },
  { id: "adria_supertwin_700sgx_ptr", nom: "SUPERTWIN 700 SGX PTR — Gamme Supertwin (Mercedes, 4X4 190cv AUT.)", gammeTwin: "Supertwin", prixUsineHt: 110471, prixPublicTtc: 155900 },
].map((v) => ({ ...v, marque: "Adria", gamme: `Fourgons — ${v.gammeTwin}`, type: "CAMPING_CAR", typeCarrosserie: "FOURGON", collection: 2027 }));


const BENIMAR_VEHICULE_IDS = ["benimar_mileo_262", "benimar_mileo_263", "benimar_mileo_268", "benimar_mileo_298", "benimar_amphitryon_968", "benimar_amphitryon_981", "benimar_amphitryon_998", "benimar_yrteo_841", "benimar_yrteo_862", "benimar_yrteo_881", "benimar_yrteo_885", "benimar_tessoro_440_up", "benimar_tessoro_463_up", "benimar_tessoro_495_up", "benimar_tessoro_425", "benimar_tessoro_443", "benimar_tessoro_444", "benimar_tessoro_461", "benimar_tessoro_463", "benimar_tessoro_468", "benimar_tessoro_481", "benimar_tessoro_483", "benimar_tessoro_488", "benimar_tessoro_498", "benimar_sport_capucine_325_up", "benimar_sport_capucine_344_up", "benimar_sport_capucine_363_up", "benimar_kaleo_625", "benimar_kaleo_640", "benimar_kaleo_663", "benimar_kaleo_695", "benimar_benivan_100_up", "benimar_benivan_120_up", "benimar_benivan_144_up", "benimar_benivan_160_up", "benimar_benivan_100", "benimar_benivan_120", "benimar_benivan_144", "benimar_benivan_160", "benimar_benivan_160_stormline"];

const BENIMAR_VEHICULES = [
  { id: "benimar_mileo_262", nom: "Mileo 262", prixUsineHt: 53490, prixPublicTtc: 71990, gamme: "Mileo", typeCarrosserie: "PROFILE" },
  { id: "benimar_mileo_263", nom: "Mileo 263", prixUsineHt: 54590, prixPublicTtc: 73490, gamme: "Mileo", typeCarrosserie: "PROFILE" },
  { id: "benimar_mileo_268", nom: "Mileo 268", prixUsineHt: 55490, prixPublicTtc: 74490, gamme: "Mileo", typeCarrosserie: "PROFILE" },
  { id: "benimar_mileo_298", nom: "Mileo 298", prixUsineHt: 55490, prixPublicTtc: 74490, gamme: "Mileo", typeCarrosserie: "PROFILE" },
  { id: "benimar_amphitryon_968", nom: "Amphitryon 968", prixUsineHt: 62990, prixPublicTtc: 85990, gamme: "Amphitryon", typeCarrosserie: "INTEGRAL" },
  { id: "benimar_amphitryon_981", nom: "Amphitryon 981", prixUsineHt: 58490, prixPublicTtc: 79990, gamme: "Amphitryon", typeCarrosserie: "INTEGRAL" },
  { id: "benimar_amphitryon_998", nom: "Amphitryon 998", prixUsineHt: 64390, prixPublicTtc: 87490, gamme: "Amphitryon", typeCarrosserie: "INTEGRAL" },
  { id: "benimar_yrteo_841", nom: "Yrteo 841", prixUsineHt: 45990, prixPublicTtc: 61990, gamme: "Yrteo", typeCarrosserie: "PROFILE" },
  { id: "benimar_yrteo_862", nom: "Yrteo 862", prixUsineHt: 45990, prixPublicTtc: 61990, gamme: "Yrteo", typeCarrosserie: "PROFILE" },
  { id: "benimar_yrteo_881", nom: "Yrteo 881", prixUsineHt: 44490, prixPublicTtc: 59990, gamme: "Yrteo", typeCarrosserie: "PROFILE" },
  { id: "benimar_yrteo_885", nom: "Yrteo 885", prixUsineHt: 45990, prixPublicTtc: 61990, gamme: "Yrteo", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_440_up", nom: "Tessoro 440 UP", prixUsineHt: 47490, prixPublicTtc: 62990, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_463_up", nom: "Tessoro 463 UP", prixUsineHt: 49490, prixPublicTtc: 65990, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_495_up", nom: "Tessoro 495 UP", prixUsineHt: 48490, prixPublicTtc: 65990, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_425", nom: "Tessoro 425", prixUsineHt: 49790, prixPublicTtc: 66990, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_443", nom: "Tessoro 443", prixUsineHt: 48490, prixPublicTtc: 65490, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_444", nom: "Tessoro 444", prixUsineHt: 49290, prixPublicTtc: 66490, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_461", nom: "Tessoro 461", prixUsineHt: 48490, prixPublicTtc: 65490, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_463", nom: "Tessoro 463", prixUsineHt: 49790, prixPublicTtc: 66990, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_468", nom: "Tessoro 468", prixUsineHt: 49990, prixPublicTtc: 66490, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_481", nom: "Tessoro 481", prixUsineHt: 46490, prixPublicTtc: 62490, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_483", nom: "Tessoro 483", prixUsineHt: 47890, prixPublicTtc: 64490, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_488", nom: "Tessoro 488", prixUsineHt: 48990, prixPublicTtc: 66490, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_tessoro_498", nom: "Tessoro 498", prixUsineHt: 50690, prixPublicTtc: 67990, gamme: "Tessoro", typeCarrosserie: "PROFILE" },
  { id: "benimar_sport_capucine_325_up", nom: "Sport Capucine 325 UP", prixUsineHt: 48990, prixPublicTtc: 64990, gamme: "Sport", typeCarrosserie: "CAPUCINE" },
  { id: "benimar_sport_capucine_344_up", nom: "Sport Capucine 344 UP", prixUsineHt: 49490, prixPublicTtc: 65990, gamme: "Sport", typeCarrosserie: "CAPUCINE" },
  { id: "benimar_sport_capucine_363_up", nom: "Sport Capucine 363 UP", prixUsineHt: 48990, prixPublicTtc: 64990, gamme: "Sport", typeCarrosserie: "CAPUCINE" },
  { id: "benimar_kaleo_625", nom: "Kaleo 625", prixUsineHt: 42990, prixPublicTtc: 55990, gamme: "Kaleo", typeCarrosserie: "PROFILE" },
  { id: "benimar_kaleo_640", nom: "Kaleo 640", prixUsineHt: 40490, prixPublicTtc: 52990, gamme: "Kaleo", typeCarrosserie: "PROFILE" },
  { id: "benimar_kaleo_663", nom: "Kaleo 663", prixUsineHt: 42990, prixPublicTtc: 56490, gamme: "Kaleo", typeCarrosserie: "PROFILE" },
  { id: "benimar_kaleo_695", nom: "Kaleo 695", prixUsineHt: 42990, prixPublicTtc: 56490, gamme: "Kaleo", typeCarrosserie: "PROFILE" },
  { id: "benimar_benivan_100_up", nom: "Benivan 100 UP", prixUsineHt: 39990, prixPublicTtc: 52990, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_120_up", nom: "Benivan 120 UP", prixUsineHt: 41090, prixPublicTtc: 54490, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_144_up", nom: "Benivan 144 UP", prixUsineHt: 41090, prixPublicTtc: 54490, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_160_up", nom: "Benivan 160 UP", prixUsineHt: 43490, prixPublicTtc: 57990, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_100", nom: "Benivan 100", prixUsineHt: 43990, prixPublicTtc: 58990, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_120", nom: "Benivan 120", prixUsineHt: 44990, prixPublicTtc: 60490, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_144", nom: "Benivan 144", prixUsineHt: 44490, prixPublicTtc: 59990, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_160", nom: "Benivan 160", prixUsineHt: 45990, prixPublicTtc: 61990, gamme: "Benivan", typeCarrosserie: "FOURGON" },
  { id: "benimar_benivan_160_stormline", nom: "Benivan 160 Stormline", prixUsineHt: 51990, prixPublicTtc: 67990, gamme: "Benivan", typeCarrosserie: "FOURGON" },
].map((v) => ({ ...v, marque: "Benimar", type: "CAMPING_CAR", collection: 2027 }));

const BENIMAR_OPTIONS = [
  { id: "benimar_opt_0_moteur_fiat_160_ch_vs_140_ch", nom: "Moteur FIAT 160 ch (vs 140 ch)", achatHt: 1050, cessionPose: 0, prixTtc: 1490, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_1_moteur_fiat_180_ch_vs_140_ch_boite_auto_", nom: "Moteur FIAT 180 ch (vs 140 ch, boîte auto obligatoire)", achatHt: 1624, cessionPose: 0, prixTtc: 2290, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_2_boite_automatique_fiat", nom: "Boîte automatique FIAT", achatHt: 2440, cessionPose: 0, prixTtc: 3390, poids: 40,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_3_chassis_heavy_4400_kg_fiat_reservoir_90l", nom: "Châssis Heavy 4400 kg FIAT (réservoir 90L)", achatHt: 1031, cessionPose: 0, prixTtc: 1490, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","O","O","O","O","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_4_moteur_ford_165_ch_vs_130_ch", nom: "Moteur FORD 165 ch (vs 130 ch)", achatHt: 1031, cessionPose: 0, prixTtc: 1490, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_5_boite_automatique_ford", nom: "Boîte automatique FORD", achatHt: 1476, cessionPose: 0, prixTtc: 2090, poids: 40,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_6_chassis_heavy_4100_kg_ford_pack_northaut", nom: "Châssis Heavy 4100 kg FORD (Pack Northautokapp obligatoire)", achatHt: 734, cessionPose: 0, prixTtc: 990, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_7_boite_automatique_citroen", nom: "Boîte automatique CITROËN", achatHt: 2440, cessionPose: 0, prixTtc: 3390, poids: 40,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_8_moteur_citroen_140_ch_vs_120_ch", nom: "Moteur Citroën 140 ch (vs 120 ch)", achatHt: 1550, cessionPose: 0, prixTtc: 1990, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "benimar_opt_9_pack_plus_mileo", nom: "PACK PLUS (Mileo)", achatHt: 2959, cessionPose: 0, prixTtc: 3990, poids: 63,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_10_pack_winter_mileo_pack_plus_obligatoire", nom: "PACK WINTER (Mileo, Pack Plus obligatoire)", achatHt: 808, cessionPose: 0, prixTtc: 1090, poids: 15,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_11_pack_northautokapp_mileo_pack_plus_oblig", nom: "PACK NORTHAUTOKAPP (Mileo, Pack Plus obligatoire)", achatHt: 5660, cessionPose: 0, prixTtc: 7990, poids: 55,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_12_northautokapp_alde_mileo", nom: "NORTHAUTOKAPP ALDE (Mileo)", achatHt: 7076, cessionPose: 0, prixTtc: 9990, poids: 75,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_13_pack_plus_amphitryon", nom: "PACK PLUS (Amphitryon)", achatHt: 2518, cessionPose: 0, prixTtc: 3395, poids: 63,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_14_pack_winter_amphitryon_pack_plus_obligat", nom: "PACK WINTER (Amphitryon, Pack Plus obligatoire)", achatHt: 1031, cessionPose: 0, prixTtc: 1490, poids: 15,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_15_pack_northautokapp_amphitryon_pack_plus_", nom: "PACK NORTHAUTOKAPP (Amphitryon, Pack Plus obligatoire)", achatHt: 3535, cessionPose: 0, prixTtc: 4990, poids: 55,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_16_northautokapp_alde_amphitryon", nom: "NORTHAUTOKAPP ALDE (Amphitryon)", achatHt: 4951, cessionPose: 0, prixTtc: 6990, poids: 75,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_17_pack_plus_yrteo", nom: "PACK PLUS (Yrteo)", achatHt: 2073, cessionPose: 0, prixTtc: 2795, poids: 63,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_18_pack_winter_yrteo_pack_plus_obligatoire", nom: "PACK WINTER (Yrteo, Pack Plus obligatoire)", achatHt: 808, cessionPose: 0, prixTtc: 1090, poids: 15,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_19_pack_northautokapp_yrteo_pack_plus_oblig", nom: "PACK NORTHAUTOKAPP (Yrteo, Pack Plus obligatoire)", achatHt: 7076, cessionPose: 0, prixTtc: 9990, poids: 55,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_20_pack_plus_tessoro", nom: "PACK PLUS (Tessoro)", achatHt: 2073, cessionPose: 0, prixTtc: 2795, poids: 63,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_21_pack_winter_tessoro_pack_plus_obligatoir", nom: "PACK WINTER (Tessoro, Pack Plus obligatoire)", achatHt: 808, cessionPose: 0, prixTtc: 1090, poids: 15,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_22_pack_northautokapp_tessoro_pack_plus_obl", nom: "PACK NORTHAUTOKAPP (Tessoro, Pack Plus obligatoire)", achatHt: 7076, cessionPose: 0, prixTtc: 9990, poids: 55,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_23_pack_stormline_tessoro_pack_northautokap", nom: "PACK STORMLINE (Tessoro, Pack Northautokapp obligatoire)", achatHt: 750, cessionPose: 0, prixTtc: 1990, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_24_pack_plus_benivan", nom: "PACK PLUS (Benivan)", achatHt: 2959, cessionPose: 0, prixTtc: 3990, poids: 50,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_25_pack_winter_benivan_pack_plus_obligatoir", nom: "PACK WINTER (Benivan, Pack Plus obligatoire)", achatHt: 967, cessionPose: 0, prixTtc: 1290, poids: 15,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_26_pack_tecno_benivan_pack_plus_obligatoire", nom: "PACK TECNO (Benivan, Pack Plus obligatoire)", achatHt: 1995, cessionPose: 0, prixTtc: 2850, poids: 55,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_27_pack_upgrade_benivan_up_boite_auto_jante", nom: "PACK UPGRADE (Benivan UP) : boîte auto + jantes 16'' Fiat", achatHt: 2490, cessionPose: 0, prixTtc: 3490, poids: 40,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","-"]) },
  { id: "benimar_opt_28_pack_onroad_kl625", nom: "PACK ONROAD (KL625)", achatHt: 3690, cessionPose: 0, prixTtc: 4990, poids: 63,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_29_pack_onroad_kl640_kl663_kl695", nom: "PACK ONROAD (KL640 / KL663 / KL695)", achatHt: 4450, cessionPose: 0, prixTtc: 5990, poids: 63,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_30_climatisation", nom: "Climatisation", achatHt: 1154, cessionPose: 0, prixTtc: 1690, poids: 25,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_31_ambiance_madeira", nom: "Ambiance Madeira", achatHt: 660, cessionPose: 0, prixTtc: 890, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_32_ambiance_manille", nom: "Ambiance Manille", achatHt: 660, cessionPose: 0, prixTtc: 890, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_33_augmentation_de_la_masse_maximale_fiat", nom: "Augmentation de la masse maximale FIAT", achatHt: 60, cessionPose: 0, prixTtc: 80, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_34_augmentation_de_la_masse_maximale_ford", nom: "Augmentation de la masse maximale FORD", achatHt: 60, cessionPose: 0, prixTtc: 80, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_35_augmentation_de_la_masse_maximale_citroe", nom: "Augmentation de la masse maximale CITROËN", achatHt: 60, cessionPose: 0, prixTtc: 80, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_36_four", nom: "Four", achatHt: 334, cessionPose: 0, prixTtc: 490, poids: 13,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_37_moquette_textile", nom: "Moquette textile", achatHt: 232, cessionPose: 0, prixTtc: 340, poids: 7,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_38_panneau_solaire_supplementaire", nom: "Panneau solaire supplémentaire", achatHt: 334, cessionPose: 0, prixTtc: 490, poids: 12,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_39_pieds_stabilisateurs", nom: "Pieds stabilisateurs", achatHt: 198, cessionPose: 0, prixTtc: 290, poids: 10,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_40_porte_velos_a_4_rails", nom: "Porte-vélos à 4 rails", achatHt: 334, cessionPose: 0, prixTtc: 490, poids: 16,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_41_rail_de_garage_fixation", nom: "Rail de garage + fixation", achatHt: 61, cessionPose: 0, prixTtc: 90, poids: 2,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","O","O","O","O","O","-","-","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_42_rail_arriere_elastiques_caoutchoucs", nom: "Rail arrière + élastiques/caoutchoucs", achatHt: 82, cessionPose: 0, prixTtc: 120, poids: 2,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","O","O","O","-","-","-","-","O","O","O","O","O","-","-","O","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_43_supplement_matelas_dinette", nom: "Supplément matelas dînette", achatHt: 198, cessionPose: 0, prixTtc: 290, poids: 10,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","O","-","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_44_auvent_noir_3_m", nom: "Auvent noir 3 m", achatHt: 403, cessionPose: 0, prixTtc: 590, poids: 27,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","-","O","-","-","-","-","-","-","-","-","-","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_45_auvent_noir_3_5_m", nom: "Auvent noir 3,5 m", achatHt: 471, cessionPose: 0, prixTtc: 690, poids: 31,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","O","-","-","O","-","O","-","-","-","-","-","-","-","-","-","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_46_auvent_noir_4_m", nom: "Auvent noir 4 m", achatHt: 539, cessionPose: 0, prixTtc: 790, poids: 35,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["O","O","O","-","-","-","-","-","-","-","-","-","-","-","O","-","-","-","O","-","-","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_47_auvent_noir_4_5_m", nom: "Auvent noir 4,5 m", achatHt: 608, cessionPose: 0, prixTtc: 890, poids: 36,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","O","O","-","O","-","-","-","-","-","-","-","-","-","O","-","-","O","-","-","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_48_lit_d_appoint_en_cabine", nom: "Lit d'appoint en cabine", achatHt: 247, cessionPose: 0, prixTtc: 330, poids: 15,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "benimar_opt_49_option_lit_transversal_dans_le_salon", nom: "Option lit transversal dans le salon", achatHt: 247, cessionPose: 0, prixTtc: 330, poids: 15,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "benimar_opt_50_pre_equipement_electrique_pour_attelage", nom: "Pré-équipement électrique pour attelage", achatHt: 225, cessionPose: 0, prixTtc: 310, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "benimar_opt_51_toit_pop_up_blanc", nom: "Toit POP-UP blanc", achatHt: 4192, cessionPose: 0, prixTtc: 5690, poids: 125,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_52_toit_relevable_noir", nom: "Toit relevable noir", achatHt: 5168, cessionPose: 0, prixTtc: 6990, poids: 125,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_53_winter_tent_isolation_thermique_pour_toi", nom: "Winter Tent (isolation thermique pour toit POP-UP)", achatHt: 337, cessionPose: 0, prixTtc: 450, poids: 2,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_54_sellerie_modena", nom: "Sellerie Modena", achatHt: 660, cessionPose: 0, prixTtc: 890, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_55_couleur_carrosserie_blue_storm_iron_grey", nom: "Couleur carrosserie Blue Storm / Iron Grey / Artense Grey", achatHt: 668, cessionPose: 0, prixTtc: 890, poids: 0,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O","-"]) },
  { id: "benimar_opt_56_auvent_benivan_3_25_m", nom: "Auvent Benivan 3,25 m", achatHt: 862, cessionPose: 0, prixTtc: 1150, poids: 31,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","-","-","-","-"]) },
  { id: "benimar_opt_57_auvent_benivan_3_75_m", nom: "Auvent Benivan 3,75 m", achatHt: 893, cessionPose: 0, prixTtc: 1190, poids: 35,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","O","-","-"]) },
  { id: "benimar_opt_58_auvent_benivan_4_m", nom: "Auvent Benivan 4 m", achatHt: 915, cessionPose: 0, prixTtc: 1240, poids: 36,
    compat: zipCompat(BENIMAR_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","O","-"]) },
].map((o) => ({ ...o, marque: "Benimar" }));


const VEHICULES = [...DREAMER_VEHICULES, ...RAPIDO_VEHICULES, ...RAPIDO_VEHICULES_INTEGRAUX, ...RAPIDO_VEHICULES_VANS, ...ADRIA_VEHICULES_CC, ...ADRIA_VEHICULES_FOURGONS, ...BENIMAR_VEHICULES];

// ---------------------------------------------------------------------------
// OPTIONS (statut par véhicule : "O" option payante, "S" de série, "-"/absent indisponible)
// ---------------------------------------------------------------------------

const DREAMER_OPTIONS = [
  { id: "isolation_portes", nom: "Kit isolation portes arrière Grand Froid", achatHt: 191, cessionPose: 0, prixTtc: 270, poids: 2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "reservoir_chauffe", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 12,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "douchette", nom: "Douchette extérieure eau froide", achatHt: 135, cessionPose: 0, prixTtc: 190, poids: 1,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","S","S"]) },
  { id: "jantes", nom: "Jantes Stellantis alliage 16\"", achatHt: 600, cessionPose: 0, prixTtc: 800, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","O","S"]) },
  { id: "batterie_agm", nom: "2e batterie cellule AGM 95Ah", achatHt: 248, cessionPose: 0, prixTtc: 350, poids: 27,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","O","S"]) },
  { id: "moquette", nom: "Moquette cellule", achatHt: 390, cessionPose: 0, prixTtc: 550, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "toit_pano", nom: "Toit panoramique Skyview", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 20,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","-","O","-","O","-","O","-","O","-","-","-","O"]) },
  { id: "peinture_up", nom: "Peinture carrosserie gamme UP (Gris Artense / Storm Blue...)", achatHt: 1425, cessionPose: 0, prixTtc: 1900, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","O","O","-","-","O","O","-","-","O","O","-","-","-","-"]) },
  { id: "peinture_h2", nom: "Peinture carrosserie gamme H2", achatHt: 788, cessionPose: 0, prixTtc: 1050, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","-","-","O","O","-","-","O","O","-","-","-","-","-","-"]) },
  { id: "isolation_toile", nom: "Kit isolation toile de toit", achatHt: 584, cessionPose: 0, prixTtc: 820, poids: 4.6,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","O","O","-","-","O","O","-","-","O","O","-","-","-","-"]) },
  { id: "four", nom: "Four 20 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-"]) },
  { id: "couchage_appoint", nom: "Couchage d'appoint 1 place", achatHt: 248, cessionPose: 0, prixTtc: 350, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","-","-","O","S","-","-","O","S","-","-","-","-","O","S"]) },
  { id: "kit_protection_matelas_d", nom: "Kit protection matelas", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 2.2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "kit_moquette_cabine_d", nom: "Kit moquette cabine", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "kit_lino_protecteur_d", nom: "Kit lino protecteur", achatHt: 140, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_arizona_d", nom: "Sellerie TEP Arizona", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","O","S"]) },
  { id: "bvm_140_35t_hd_vs120_d", nom: "FIAT/Peugeot 140ch BVM 3,5T Heavy Duty (vs 120ch BVM 3,5T)", achatHt: 1500, cessionPose: 0, prixTtc: 2000, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "bva_140_35t_ld_vs120_d", nom: "FIAT/Peugeot 140ch BVA 3,5T Light Duty (vs 120ch BVM 3,5T)", achatHt: 3938, cessionPose: 0, prixTtc: 5250, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "bva_140_35t_ld_vs140_d", nom: "FIAT/Peugeot 140ch BVA 3,5T Light Duty (vs 140ch BVM 3,5T)", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "bva_140_425t_hd_vs140_d", nom: "FIAT/Peugeot 140ch BVA 4,25T Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 3413, cessionPose: 0, prixTtc: 4550, poids: 45,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "bva_160_35t_hd_vs120_d", nom: "FIAT/Peugeot 160ch BVA 3,5T Heavy Duty (vs 120ch BVM 3,5T)", achatHt: 5100, cessionPose: 0, prixTtc: 6800, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "bva_160_35t_hd_vs140_d", nom: "FIAT/Peugeot 160ch BVA 3,5T Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 3600, cessionPose: 0, prixTtc: 4800, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  // --- Ajouts (audit complet tarif options Dreamer 2027, V1 22/07/2026) ---
  { id: "bva_160_35t_35h_hd_vs140_d", nom: "FIAT/Peugeot 160ch BVA 3,5T 35H Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 3900, cessionPose: 0, prixTtc: 5200, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "bva_160_425t_hd_vs140_d", nom: "FIAT/Peugeot 160ch BVA 4,25T Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 4350, cessionPose: 0, prixTtc: 5800, poids: 45,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "bva_180_35t_hd_vs140_d", nom: "FIAT/Peugeot 180ch BVA 3,5T Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 5100, cessionPose: 0, prixTtc: 6800, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "bva_180_35t_ld_vs140_d", nom: "FIAT/Peugeot 180ch BVA 3,5T Light Duty (vs 140ch BVM 3,5T)", achatHt: 4875, cessionPose: 0, prixTtc: 6500, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","S","O","S","O","O","O","O","O","-","-","-","-"]) },
  { id: "bva_180_35t_35h_ld_vs140_d", nom: "FIAT/Peugeot 180ch BVA 3,5T 35H Light Duty (vs 140ch BVM 3,5T)", achatHt: 5175, cessionPose: 0, prixTtc: 6900, poids: 45,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","O","O","O","O"]) },
  { id: "bva_180_425t_hd_vs140_d", nom: "FIAT/Peugeot 180ch BVA 4,25T Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 5850, cessionPose: 0, prixTtc: 7800, poids: 45,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "roue_secours_d", nom: "Roue de secours (implique réservoir gasoil 60L)", achatHt: 263, cessionPose: 0, prixTtc: 350, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","-","-","-","-","-","-","-","-"]) },
  { id: "led_d", nom: "Projecteurs avant 100% LED", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "camera_recul_dab_d", nom: "Caméra de recul + station multimédia DAB Pioneer 6,8'' (CarPlay/Android Auto)", achatHt: 708, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","O","S"]) },
  { id: "pack_energy_d", nom: "PACK ENERGY (monté usine) : 1 batterie Lithium 150Ah + 1 panneau solaire 150W", achatHt: 758, cessionPose: 0, prixTtc: 1650, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","-","-","O","-","-","-","O","-","-","-","O","-","O"]) },
  { id: "pack_energy_souple_d", nom: "PACK ENERGY (monté usine) : 1 batterie Lithium 150Ah + 1 panneau solaire 150W souple", achatHt: 758, cessionPose: 0, prixTtc: 1650, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","O","-","-","-","O","-","-","-","O","-","-","-","-"]) },
  { id: "pack_mountain_d", nom: "PACK MOUNTAIN : chauffage Webasto 5500W, chauffe-eau gaz + électrique, plancher chauffant électrique", achatHt: 921, cessionPose: 0, prixTtc: 1400, poids: 1,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_smart_d", nom: "PACK SMART : jantes 16'' bi-ton, volant confort, habillage gris sur aérateurs", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","S","-","S","-","S","-","S","-","S","-","S","-","S","-","S"]) },
  { id: "pack_lounge_d", nom: "PACK LOUNGE : climatisation cabine automatique, chargeur induction, combiné digital", achatHt: 743, cessionPose: 0, prixTtc: 990, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_adapt_d", nom: "PACK ADAPT : régulateur de vitesse adaptatif >30km/h + capteur pluie/luminosité", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","-","O","-","O","-","O","-","O","-","O","-","O"]) },
  { id: "pack_assist_fiat_d", nom: "PACK ASSIST (uniquement FIAT) : Pack Adapt + Stop&Go, phares antibrouillard directionnels, tableau de bord 100% digital, frein de stationnement électrique, volant confort", achatHt: 1725, cessionPose: 0, prixTtc: 2300, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","-","O","-","O","-","O","-","O","-","O","-","O"]) },
  { id: "pack_vision_plus_d", nom: "PACK VISION+ : rétroviseurs extérieurs électriques, dégivrants et rabattables, détection d'angle mort", achatHt: 675, cessionPose: 0, prixTtc: 900, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_keyless_d", nom: "PACK KEYLESS : verrouillage/démarrage sans clé + frein de stationnement électrique", achatHt: 863, cessionPose: 0, prixTtc: 1150, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_essential_d", nom: "PACK ESSENTIAL : 140ch BVA, Pack Energy (panneau solaire 150W + batterie Lithium 150Ah), Pack Smart, caméra de recul DAB Pioneer 6,8'', sellerie Fusion, décoration extérieure", achatHt: 2933, cessionPose: 0, prixTtc: 4000, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","-","O","-","-","-","-","-","-","-","-","-"]) },
].map((o) => ({ ...o, marque: "Dreamer" }));

const RAPIDO_OPTIONS = [
  { id: "toit_pano_r", nom: "Toit panoramique Skyview", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 20,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["S","S","S","S","S","-","-","-","-"]) },
  { id: "truma_combi", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique)", achatHt: 531, cessionPose: 0, prixTtc: 750, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "alde_confort", nom: "Chauffage central ALDE Confort Plus Arctic", achatHt: 3152, cessionPose: 0, prixTtc: 4450, poids: 65,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","O","-","-"]) },
  { id: "plancher_chauffant_r", nom: "Plancher chauffant cellule 230V", achatHt: 460, cessionPose: 0, prixTtc: 650, poids: 7,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "reservoir_chauffe_r", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 15,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_palma", nom: "Sellerie TEP Palma (mobilier Palatina)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","-","-","-","-","-","-"]) },
  { id: "lit_pavillon", nom: "Lit de pavillon relevable électriquement (2 pers.)", achatHt: 1488, cessionPose: 0, prixTtc: 2100, poids: 45,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","O","O","O"]) },
  { id: "four23", nom: "Four 23 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 22,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","-","O","O","O"]) },
  { id: "lit_bas_reglable", nom: "Lit permanent bas réglable en hauteur (vérins électriques)", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","O","-","-","O","-","O","O","O"]) },
  { id: "batterie_2e", nom: "2e batterie cellule LITHIUM 150Ah", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","O","O","O","O","O","O","O","O"]) },
  { id: "convertisseur", nom: "Convertisseur 2000W avec coupe batterie", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","S","S","-","S","-","S"]) },
  { id: "bva_fiat_peugeot", nom: "Boîte de vitesses automatique Fiat/Peugeot", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","O","S","O","S"]) },
  { id: "moquette_chauffante_alde_r", nom: "Moquette chauffante ALDE cabine (oblige chauffage ALDE)", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 6,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","O","-","-"]) },
  { id: "sellerie_milan_r", nom: "Sellerie TEP Milan", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_noumea_r", nom: "Sellerie TEP Noumea (mobilier Aurora)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","-","-","-","-","-","-"]) },
  { id: "sellerie_alba_r", nom: "Sellerie Tissu Alba", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "four22_r", nom: "Four 22 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","O","-","-","-"]) },
  { id: "surmatelas_r", nom: "Sur-matelas à mémoire de forme sur lit permanent", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 6,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","-","-","O","-","-","O","O"]) },
  { id: "kit_lino_r", nom: "Kit lino protecteur", achatHt: 140, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "douchette_r", nom: "Douchette extérieure eau chaude/froide", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 1,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "fiat_160ch_r", nom: "FIAT/Peugeot 160 ch (vs 140 ch)", achatHt: 1163, cessionPose: 0, prixTtc: 1550, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "attelage_r", nom: "Attelage 2000 kg maxi (sous réserve PTRA)", achatHt: 1063, cessionPose: 0, prixTtc: 1420, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "led_r", nom: "Projecteurs avant 100% LED", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "retro_double_vision_r", nom: "Rétroviseurs extérieurs double vision", achatHt: 213, cessionPose: 0, prixTtc: 280, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["S","S","S","S","S","S","S","S","S"]) },
  { id: "retro_rabattables_r", nom: "Rétroviseurs extérieurs rabattables électriquement", achatHt: 263, cessionPose: 0, prixTtc: 350, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","-","-","-","-"]) },
  { id: "verins_stabilisation_r", nom: "Vérins de stabilisation", achatHt: 128, cessionPose: 0, prixTtc: 180, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_energy_r", nom: "PACK ENERGY (monté usine) : batterie Lithium + panneau solaire 150W", achatHt: 758, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","O","S","O","S"]) },
  { id: "pack_smart_r", nom: "PACK SMART : jantes 16'' bi-ton, volant confort, habillage aérateurs", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","O","S","O","S"]) },
  { id: "pack_lounge_r", nom: "PACK LOUNGE : climatisation cabine auto, chargeur induction, combiné digital", achatHt: 743, cessionPose: 0, prixTtc: 990, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_adapt_r", nom: "PACK ADAPT : régulateur adaptatif + capteur pluie/luminosité", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_keyless_full_r", nom: "PACK KEYLESS : accès/démarrage sans clé + frein de stationnement électrique", achatHt: 863, cessionPose: 0, prixTtc: 1150, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","-","-","O","-","O","-"]) },
  { id: "pack_keyless_basic_r", nom: "PACK KEYLESS : accès/démarrage sans clé", achatHt: 413, cessionPose: 0, prixTtc: 550, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","O","O","-","O","-","O"]) },
  { id: "nav_pioneer_a_r", nom: "Navigation multimédia DAB Pioneer 9\" (CarPlay/Android Auto)", achatHt: 744, cessionPose: 0, prixTtc: 1050, poids: 2,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","-","-","O","-","O","-"]) },
  { id: "nav_pioneer_b_r", nom: "Navigation multimédia DAB Pioneer 9\" (CarPlay/Android Auto) — variante", achatHt: 425, cessionPose: 0, prixTtc: 600, poids: 2,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","O","O","-","O","-","O"]) },
  // --- Ajouts (audit complet tarif V2 20/05/2026, lignes manquantes) ---
  { id: "surmatelas900_r", nom: "Sur-matelas à mémoire de forme sur lit permanent (900€)", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 6,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","O","O","-","-","O","-","-"]) },
  { id: "kit_protection_matelas150_r", nom: "Kit protection matelas (150€)", achatHt: 106, cessionPose: 0, prixTtc: 150, poids: 1.3,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","-","-","O","-","-","O","O"]) },
  { id: "kit_protection_matelas300_r", nom: "Kit protection matelas (300€)", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 2.2,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","O","O","-","-","O","-","-"]) },
  { id: "batterie_lithium150_r", nom: "Batterie cellule LITHIUM 150Ah (coupleur/séparateur/booster)", achatHt: 567, cessionPose: 0, prixTtc: 800, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","S","S","-","S","-","S"]) },
  { id: "audio_symphonie_r", nom: "Système Audio Symphonie", achatHt: 708, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "moquette_cellule_cabine_r", nom: "Moquette cellule et cabine", achatHt: 744, cessionPose: 0, prixTtc: 1050, poids: 11,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "panneau_solaire150_r", nom: "Panneau solaire 150W (monté usine)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 9,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","S","S","-","S","-","S"]) },
  { id: "fiat_140ch_bva425t_vs_bvm35_r", nom: "FIAT/Peugeot 140 ch, BVA 4,25T (vs 140 ch BVM 3,5T)", achatHt: 3413, cessionPose: 0, prixTtc: 4550, poids: 45,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","O","O","-","-","O","-","-","-"]) },
  { id: "fiat_160ch_bva425t_vs_bvm35_r", nom: "FIAT/Peugeot 160 ch, BVA 4,25T (vs 140 ch BVM 3,5T)", achatHt: 4350, cessionPose: 0, prixTtc: 5800, poids: 45,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","O","O","-","-","O","-","-","-"]) },
  { id: "fiat_160ch_bva44t_vs_bva35_r", nom: "FIAT/Peugeot 160 ch, BVA 4,4T (vs 140 ch BVA 3,5T)", achatHt: 2775, cessionPose: 0, prixTtc: 3700, poids: 40,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","O","O","-","O","-","O"]) },
  { id: "fiat_160ch_bva44t_vs_bvm35_r", nom: "FIAT/Peugeot 160 ch, BVA 4,4T (vs 140 ch BVM 3,5T)", achatHt: 5213, cessionPose: 0, prixTtc: 6950, poids: 45,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","-"]) },
  { id: "fiat_180ch_bva35t_r", nom: "FIAT/Peugeot 180 ch, BVA 3,5T (vs 140 ch, oblige BVA)", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","O","O","O","O","O","O","O","O"]) },
  { id: "fiat_180ch_bva44t_var1_r", nom: "FIAT/Peugeot 180 ch, BVA 4,4T (vs 140 ch BVA 3,5T)", achatHt: 4275, cessionPose: 0, prixTtc: 5700, poids: 40,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","O","O","-","-","-","-"]) },
  { id: "fiat_180ch_bva44t_var2_r", nom: "FIAT/Peugeot 180 ch, BVA 4,4T (vs 140 ch BVA 3,5T) — variante", achatHt: 4050, cessionPose: 0, prixTtc: 5400, poids: 40,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","O","-","O"]) },
  { id: "fiat_180ch_bva44t_vs_bvm35_r", nom: "FIAT/Peugeot 180 ch, BVA 4,4T (vs 140 ch BVM 3,5T)", achatHt: 6488, cessionPose: 0, prixTtc: 8650, poids: 45,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","-","O","-"]) },
  { id: "commandes_volant_radio_r", nom: "Commandes au volant pour radio", achatHt: 225, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["S","S","S","S","S","S","S","S","S"]) },
].map((o) => ({ ...o, marque: "Rapido" }));

const RAPIDO_OPTIONS_INTEGRAUX = [
  { id: "pack_energy_i", nom: "PACK ENERGY (batterie Lithium + panneau solaire 150W)", achatHt: 758, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","-","-","-","-","-","-","-","-","-"]) },
  { id: "pack_smart_i", nom: "PACK SMART (jantes 16'' bi-ton, volant confort)", achatHt: 825, cessionPose: 0, prixTtc: 1100, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","-","-","-","-","-","-"]) },
  { id: "pack_lounge_i", nom: "PACK LOUNGE (climatisation auto + chargeur induction)", achatHt: 743, cessionPose: 0, prixTtc: 990, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "pack_drive_assist_66_96", nom: "PACK DRIVE ASSIST i66M/i96M", achatHt: 3075, cessionPose: 0, prixTtc: 4100, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","O","O","O","-","-"]) },
  { id: "pack_drive_assist_166_196", nom: "PACK DRIVE ASSIST i166M/i196M", achatHt: 2175, cessionPose: 0, prixTtc: 2900, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","O","O"]) },
  { id: "bva_fiat_i", nom: "Boîte de vitesses automatique FIAT", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","-","-","-","-","-","-"]) },
  { id: "fiat_160ch_i", nom: "FIAT 160 ch (vs 140 ch)", achatHt: 1163, cessionPose: 0, prixTtc: 1550, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "chassis_heavy", nom: "Châssis HEAVY : PTAC 4,5T (réservoir 93L inclus)", achatHt: 1875, cessionPose: 0, prixTtc: 2500, poids: 40,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","S","O","S","S","S"]) },
  { id: "frein_stationnement_i", nom: "Frein de stationnement électrique", achatHt: 450, cessionPose: 0, prixTtc: 600, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","-","-","-","S","S","S","S","S","S"]) },
  { id: "led_i", nom: "Projecteurs avant 100% LED", achatHt: 921, cessionPose: 0, prixTtc: 1300, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","S","S"]) },
  { id: "retro_double_vision", nom: "Rétroviseurs extérieurs double vision", achatHt: 213, cessionPose: 0, prixTtc: 280, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","S","S","S","S","S","S"]) },
  { id: "verins_stabilisation", nom: "Vérins de stabilisation", achatHt: 128, cessionPose: 0, prixTtc: 180, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","S","O","S","S","S"]) },
  { id: "truma_combi_a_i", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique) — gamme C/8F", achatHt: 531, cessionPose: 0, prixTtc: 750, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "truma_combi_b_i", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique) — 850F/866F OL/896F OL", achatHt: 446, cessionPose: 0, prixTtc: 630, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "truma_combi_c_i", nom: "TRUMA Combi 6 EH (gaz + électrique) — gamme 80dF", achatHt: 390, cessionPose: 0, prixTtc: 550, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "alde_confort_i", nom: "Chauffage central ALDE Confort Plus Arctic", achatHt: 3542, cessionPose: 0, prixTtc: 5000, poids: 65,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","-","O","-","-","-","-","-","-"]) },
  { id: "plancher_chauffant_i", nom: "Plancher chauffant cellule 230V", achatHt: 460, cessionPose: 0, prixTtc: 650, poids: 7,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "plancher_chauffant_alde_i", nom: "Plancher chauffant cellule ALDE à eau chaude", achatHt: 460, cessionPose: 0, prixTtc: 650, poids: 8,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","-","O","-","O","-","O","O","O"]) },
  { id: "moquette_chauffante_alde_i", nom: "Moquette chauffante ALDE cabine", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 6,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","-","O","-","O","-","O","O","O"]) },
  { id: "reservoir_chauffe_i", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 15,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","S","S","S","S","S","S","S","S","S","S","S"]) },
  { id: "clim_cellule_truma_i", nom: "Climatisation cellule TRUMA 2500W (monté usine)", achatHt: 1417, cessionPose: 0, prixTtc: 2000, poids: 45,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","O","O"]) },
  { id: "tiroir_rangement_i", nom: "Tiroir de rangement extérieur coulissant (45L / 25kg)", achatHt: 496, cessionPose: 0, prixTtc: 700, poids: 18,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "sellerie_milan_i", nom: "Sellerie TEP Milan", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "sellerie_cuir_austin_i", nom: "Sellerie cuir Austin", achatHt: 1771, cessionPose: 0, prixTtc: 2500, poids: 8,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_cuir_braga_i", nom: "Sellerie cuir Braga", achatHt: 1771, cessionPose: 0, prixTtc: 2500, poids: 8,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_palma_i", nom: "Sellerie TEP Palma (mobilier Palatina)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","S","S","S","S","S","S"]) },
  { id: "sellerie_noumea_i", nom: "Sellerie TEP Noumea (mobilier Aurora)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","S","S","S","S","S","S"]) },
  { id: "sellerie_budapest_i", nom: "Sellerie Tissu Budapest", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_alba_i", nom: "Sellerie Tissu Alba", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "refrigerateur_compression_i", nom: "Réfrigérateur à compression", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "four23_i", nom: "Four 23 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 22,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "tectower_i", nom: "TEC-Tower : combiné réfrigérateur et four 25L avec grill", achatHt: 885, cessionPose: 0, prixTtc: 1250, poids: 21,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","O","O","O","S","S"]) },
  { id: "lit_bas_30cm_i", nom: "Lit permanent bas réglable (~30cm) vérins électriques", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","-","O","-","O","O","-","-","S","S","-","S"]) },
  { id: "lit_bas_20cm_i", nom: "Lit permanent bas réglable (~20cm) vérins électriques", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","O","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "surmatelas_i", nom: "Sur-matelas à mémoire de forme sur lit permanent (400€)", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 6,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","O","O","-","O","-","O","O","-","-","O","O","-","S"]) },
  // --- Ajouts (audit complet du tarif options V2 20/05/2026, lignes manquantes) ---
  { id: "fiat_160ch_bva44_vs_bva35_i", nom: "FIAT 160 ch + BVA 4,4T (vs 140 ch BVA 3,5T)", achatHt: 2775, cessionPose: 0, prixTtc: 3700, poids: 40,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","O","O","-","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "fiat_160ch_bva44_vs_bvm35_i", nom: "FIAT 160 ch + BVA 4,4T (vs 140 ch BVM 3,5T)", achatHt: 5213, cessionPose: 0, prixTtc: 6950, poids: 45,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","-","-","O","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "fiat_180ch_35t_i", nom: "FIAT 180 ch 3,5T (vs 140 ch, boîte auto obligatoire)", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "fiat_180ch_44t_i", nom: "FIAT 180 ch 4,4T (vs 140 ch 3,5T, boîte auto obligatoire)", achatHt: 4050, cessionPose: 0, prixTtc: 5400, poids: 40,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "fiat_180ch_45t_i", nom: "FIAT 180 ch 4,5T (vs 140 ch 3,5T)", achatHt: 4913, cessionPose: 0, prixTtc: 6550, poids: 40,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "phares_antibrouillard_i", nom: "Phares antibrouillard avant", achatHt: 263, cessionPose: 0, prixTtc: 350, poids: 1,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "suspension_acs_light_i", nom: "Suspension essieu avant ACS (châssis LIGHT)", achatHt: 1425, cessionPose: 0, prixTtc: 1900, poids: 3,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "suspension_acs_heavy_i", nom: "Suspension essieu avant ACS (châssis HEAVY)", achatHt: 1800, cessionPose: 0, prixTtc: 2400, poids: 3,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "alko_comfort_light_i", nom: "Suspension AL-KO Comfort Drive (châssis LIGHT)", achatHt: 1425, cessionPose: 0, prixTtc: 1900, poids: 10,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","-","O","-","-","-"]) },
  { id: "alko_comfort_heavy_i", nom: "Suspension AL-KO Comfort Drive (châssis HEAVY)", achatHt: 2175, cessionPose: 0, prixTtc: 2900, poids: 10,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","O","O","O","O","O"]) },
  { id: "attelage_profile_i", nom: "Attelage 2000 kg (profilés / 850F)", achatHt: 1063, cessionPose: 0, prixTtc: 1420, poids: 60,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "attelage_integral_i", nom: "Attelage 2000 kg (Intégraux base Mercedes)", achatHt: 1771, cessionPose: 0, prixTtc: 2360, poids: 55,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "sieges_aguti_i", nom: "Sièges cabine AGUTI rotatifs GIS Liner (chauffés/ventilés)", achatHt: 779, cessionPose: 0, prixTtc: 1100, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","O","O"]) },
  { id: "navigation_dab9_var1_i", nom: "Navigation DAB Pioneer 9'' CarPlay/Android Auto (C55i/850F)", achatHt: 744, cessionPose: 0, prixTtc: 1050, poids: 2,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","-","-","O","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "navigation_dab9_var2_i", nom: "Navigation DAB Pioneer 9'' CarPlay/Android Auto (autres profilés/intégraux)", achatHt: 425, cessionPose: 0, prixTtc: 600, poids: 2,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","O","O","-","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "habillage_grand_froid_i", nom: "Habillage extérieur Grand Froid", achatHt: 496, cessionPose: 0, prixTtc: 700, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "baies_cabine_double_vitrage_i", nom: "Baies cabine latérales double vitrage (sauf porte chauffeur)", achatHt: 425, cessionPose: 0, prixTtc: 600, poids: 10,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","O","O","O","O","O","-","O","-","O","O","O"]) },
  { id: "sans_lit_cabine_fixe_i", nom: "Sans lit cabine, avec table salon pied fixe", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "sans_lit_cabine_telescopique_i", nom: "Sans lit cabine, avec table salon pied télescopique", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "surmatelas900_i", nom: "Sur-matelas à mémoire de forme sur lit permanent (900€)", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 6,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","-","-","O","-","O","-","-","O","O","-","-","S","-"]) },
  { id: "kit_protection_matelas150_i", nom: "Kit protection matelas (150€)", achatHt: 106, cessionPose: 0, prixTtc: 150, poids: 1.3,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","O","O","-","O","-","O","O","-","-","O","O","-","O"]) },
  { id: "kit_protection_matelas300_i", nom: "Kit protection matelas (300€)", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 2.2,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","-","-","O","-","O","-","-","O","O","-","-","O","-"]) },
  { id: "batterie_lithium150_i", nom: "Batterie cellule LITHIUM 150Ah (coupleur/séparateur/booster)", achatHt: 567, cessionPose: 0, prixTtc: 800, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","S","S","-","S","S","-","-","-","-","-","-","-","-","-"]) },
  { id: "batterie2_lithium150_i", nom: "2e batterie cellule LITHIUM 150Ah (total 300Ah)", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "convertisseur2000w_i", nom: "Convertisseur 2000W avec coupe batterie", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","S","S","-","S","S","-","-","-","O","O","O","O","S","S"]) },
  { id: "audio_symphonie_i", nom: "Système Audio Symphonie", achatHt: 708, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","S","S"]) },
  { id: "moquette_cellule_i", nom: "Moquette cellule", achatHt: 744, cessionPose: 0, prixTtc: 1050, poids: 9,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","O","O"]) },
  { id: "moquette_cellule_cabine_i", nom: "Moquette cellule et cabine", achatHt: 744, cessionPose: 0, prixTtc: 1050, poids: 11,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","-","-"]) },
  { id: "kit_moquette_cabine_i", nom: "Kit moquette cabine", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","S","S"]) },
  { id: "kit_lino_protecteur_i", nom: "Kit lino protecteur", achatHt: 140, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "panneau_solaire150_i", nom: "Panneau solaire 150W (monté usine)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 9,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","S","S","-","S","S","O","O","O","O","O","O","O","S","S"]) },
  { id: "douchette_exterieure_i", nom: "Douchette extérieure eau chaude/froide", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 1,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","S","S","S","S","S","S"]) },
].map((o) => ({ ...o, marque: "Rapido" }));

const RAPIDO_OPTIONS_VANS = [
  { id: "peinture_artense_var1_van", nom: "Peinture carrosserie Gris Artense / Expedition Grey / Iron Grey", achatHt: 788, cessionPose: 0, prixTtc: 1050, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","O","-","O"]) },
  { id: "peinture_artense_var2_van", nom: "Peinture carrosserie Gris Artense / Expedition Grey / Iron Grey — variante", achatHt: 1125, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["-","-","-","O","-"]) },
  { id: "toit_pano_van", nom: "Toit panoramique Skyview", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 20,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","-","O"]) },
  { id: "baie_arriere_gauche_van", nom: "Baie porte arrière gauche", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","-","-","S","O"]) },
  { id: "baie_arriere_droite_van", nom: "Baie porte arrière droite", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","O","-","S","O"]) },
  { id: "isolation_portes_van", nom: "Kit isolation portes arrière Grand Froid", achatHt: 191, cessionPose: 0, prixTtc: 270, poids: 2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "truma_combi_van", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique)", achatHt: 531, cessionPose: 0, prixTtc: 750, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","-","O","O"]) },
  { id: "webasto_5500w_van", nom: "Chauffage carburant WEBASTO 5500W", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["-","-","O","-","-"]) },
  { id: "chauffe_eau_whale_van", nom: "Chauffe-eau WHALE 8L avec résistance électrique (gaz + électrique)", achatHt: 460, cessionPose: 0, prixTtc: 650, poids: 1,
    compat: zipCompat(RAPIDO_VANS_IDS, ["-","-","O","-","-"]) },
  { id: "plancher_chauffant_van", nom: "Plancher chauffant cellule 230V", achatHt: 319, cessionPose: 0, prixTtc: 450, poids: 5,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "reservoir_chauffe_van", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 12,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "sellerie_milan_van", nom: "Sellerie TEP Milan", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "sellerie_palma_van", nom: "Sellerie TEP Palma (mobilier Palatina)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","-","-","-"]) },
  { id: "sellerie_noumea_van", nom: "Sellerie TEP Noumea (mobilier Aurora)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","-","-","-"]) },
  { id: "sellerie_alba_van", nom: "Sellerie Tissu Alba", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "four20_van", nom: "Four 20 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","-","O","O","O"]) },
  { id: "four22_van", nom: "Four 22 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_VANS_IDS, ["-","O","-","-","-"]) },
  { id: "surmatelas400_van", nom: "Sur-matelas à mémoire de forme sur lit permanent (400€)", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 6,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","-"]) },
  { id: "surmatelas900_van", nom: "Sur-matelas à mémoire de forme sur lit permanent (900€)", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 6,
    compat: zipCompat(RAPIDO_VANS_IDS, ["-","-","-","-","O"]) },
  { id: "kit_protection_matelas_van", nom: "Kit protection matelas", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 2.2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "batterie_lithium150_van", nom: "Batterie cellule LITHIUM 150Ah (coupleur/séparateur/booster)", achatHt: 567, cessionPose: 0, prixTtc: 800, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","-","-","-"]) },
  { id: "convertisseur_van", nom: "Convertisseur 2000W avec coupe batterie", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 5,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","-","-","-"]) },
  { id: "moquette_van", nom: "Moquette cellule", achatHt: 390, cessionPose: 0, prixTtc: 550, poids: 5,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "kit_moquette_cabine_van", nom: "Kit moquette cabine", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "kit_lino_van", nom: "Kit lino protecteur", achatHt: 140, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "panneau_solaire150_van", nom: "Panneau solaire 150W (monté usine)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 9,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","-","-","-"]) },
  { id: "douchette_van", nom: "Douchette extérieure eau chaude/froide", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 1,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","S","S","S"]) },
  { id: "bva_van", nom: "Boîte de vitesses automatique Fiat/Peugeot", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","O","O","O"]) },
  { id: "chassis_425t_hd_van", nom: "FIAT/Peugeot 4,25T HD (oblige BVA)", achatHt: 975, cessionPose: 0, prixTtc: 1300, poids: 40,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "fiat_160ch_van", nom: "FIAT/Peugeot 160 ch (vs 140 ch)", achatHt: 1163, cessionPose: 0, prixTtc: 1550, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "fiat_180ch_van", nom: "FIAT/Peugeot 180 ch (vs 140 ch, oblige BVA)", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "frein_stationnement_van", nom: "Frein de stationnement électrique", achatHt: 450, cessionPose: 0, prixTtc: 600, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","-","-","-"]) },
  { id: "led_van", nom: "Projecteurs avant 100% LED", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "renfort_suspension_van", nom: "Renfort pneumatique suspension essieu arrière sans compresseur", achatHt: 713, cessionPose: 0, prixTtc: 1010, poids: 9,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "roue_secours_van", nom: "Roue de secours (implique réservoir gasoil 60L)", achatHt: 263, cessionPose: 0, prixTtc: 350, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","-","-","-","-"]) },
  { id: "commandes_volant_radio_van", nom: "Commandes au volant pour radio", achatHt: 225, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","S","S","S"]) },
  { id: "navigation_dab9_var1_van", nom: "Navigation DAB Pioneer 9'' CarPlay/Android Auto", achatHt: 744, cessionPose: 0, prixTtc: 1050, poids: 2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["-","-","O","O","O"]) },
  { id: "navigation_dab9_var2_van", nom: "Navigation DAB Pioneer 9'' CarPlay/Android Auto — variante", achatHt: 425, cessionPose: 0, prixTtc: 600, poids: 2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","-","-","-"]) },
  { id: "pack_energy_van", nom: "PACK ENERGY (monté usine) : 1 batterie Lithium + 1 panneau solaire 150W", achatHt: 758, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","O","O","O"]) },
  { id: "pack_smart_van", nom: "PACK SMART : jantes 16'' bi-ton, volant confort, habillage gris aérateurs", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","O","O","O"]) },
  { id: "pack_lounge_van", nom: "PACK LOUNGE : climatisation cabine automatique, chargeur induction, combiné digital", achatHt: 743, cessionPose: 0, prixTtc: 990, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "pack_adapt_van", nom: "PACK ADAPT : régulateur de vitesse adaptatif >30km/h + capteur pluie/luminosité", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "pack_assist_fiat_van", nom: "PACK ASSIST (uniquement FIAT) : Pack Adapt + Stop&Go, phares antibrouillard directionnels, tableau de bord 100% digital, frein de stationnement électrique, volant confort", achatHt: 1725, cessionPose: 0, prixTtc: 2300, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "pack_vision_plus_van", nom: "PACK VISION+ : rétroviseurs extérieurs électriques, dégivrants et rabattables, détection d'angle mort", achatHt: 675, cessionPose: 0, prixTtc: 900, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "pack_keyless_full_van", nom: "PACK KEYLESS : verrouillage/démarrage sans clé + frein de stationnement électrique", achatHt: 863, cessionPose: 0, prixTtc: 1150, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["-","-","O","O","O"]) },
  { id: "pack_keyless_basic_van", nom: "PACK KEYLESS : verrouillage/démarrage sans clé", achatHt: 413, cessionPose: 0, prixTtc: 550, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","-","-","-"]) },
].map((o) => ({ ...o, marque: "Rapido" }));

const OPTIONS = [...DREAMER_OPTIONS, ...RAPIDO_OPTIONS, ...RAPIDO_OPTIONS_INTEGRAUX, ...RAPIDO_OPTIONS_VANS, ...BENIMAR_OPTIONS];

module.exports = { VEHICULES, OPTIONS };
