// Données de référence extraites des tarifs distributeur/public 2027 (Dreamer + Rapido),
// reprises telles quelles depuis le prototype validé. Ce fichier est la source de vérité
// pour le script d'import scripts/seed.js — ne pas modifier sans mettre à jour les deux en parallèle.

function zipCompat(ids, statuts) {
  const map = {};
  ids.forEach((id, i) => { map[id] = statuts[i]; });
  return map;
}

// ---------------------------------------------------------------------------
// VÉHICULES
// ---------------------------------------------------------------------------

const DREAMER_VEHICULE_IDS = ["d43", "d43p", "d43up", "d43upp", "d55", "d55p", "d55up", "d55upp", "d68", "d68p", "d68up", "d68upp", "cf", "cfp", "cs", "csp"];

const DREAMER_VEHICULES = [
  { id: "d43", nom: "D43 FUN 120cv", prixUsineHt: 39803.67, prixPublicTtc: 54500 },
  { id: "d43p", nom: "D43 FUN+ 140cv", prixUsineHt: 43763.67, prixPublicTtc: 59900 },
  { id: "d43up", nom: "D43 UP FUN 120cv", prixUsineHt: 44203.67, prixPublicTtc: 60500 },
  { id: "d43upp", nom: "D43 UP FUN+ 140cv", prixUsineHt: 48163.67, prixPublicTtc: 65900 },
  { id: "d55", nom: "D55 FUN 140cv", prixUsineHt: 43030.33, prixPublicTtc: 58900 },
  { id: "d55p", nom: "D55 FUN+ 140cv", prixUsineHt: 45963.67, prixPublicTtc: 62900 },
  { id: "d55up", nom: "D55 UP FUN 140cv", prixUsineHt: 47430.33, prixPublicTtc: 64900 },
  { id: "d55upp", nom: "D55 UP FUN+ 140cv", prixUsineHt: 50363.67, prixPublicTtc: 68900 },
  { id: "d68", nom: "D68 FUN 140cv", prixUsineHt: 44497.0, prixPublicTtc: 60900 },
  { id: "d68p", nom: "D68 FUN+ 140cv", prixUsineHt: 47430.33, prixPublicTtc: 64900 },
  { id: "d68up", nom: "D68 UP FUN 140cv", prixUsineHt: 48897.0, prixPublicTtc: 66900 },
  { id: "d68upp", nom: "D68 UP FUN+ 140cv", prixUsineHt: 51097.0, prixPublicTtc: 69900 },
  { id: "cf", nom: "CAMPER FIVE FUN 140cv", prixUsineHt: 46403.67, prixPublicTtc: 63500 },
  { id: "cfp", nom: "CAMPER FIVE FUN+ 140cv", prixUsineHt: 49337.0, prixPublicTtc: 67500 },
  { id: "cs", nom: "CAMPER SPORT FUN 140cv", prixUsineHt: 46403.67, prixPublicTtc: 63500 },
  { id: "csp", nom: "CAMPER SPORT FUN+ 140cv", prixUsineHt: 49337.0, prixPublicTtc: 67500 },
].map((v) => ({ ...v, marque: "Dreamer", gamme: "FUN", type: "CAMPING_CAR", collection: 2027 }));

const RAPIDO_VEHICULE_IDS = ["r_c03", "r_c50", "r_c55", "r_c66ol", "r_c86ol", "r_606f", "r_666fol", "r_686f", "r_696fol"];

const RAPIDO_VEHICULES = [
  { id: "r_c03", nom: "C03", prixUsineHt: 53124.10, prixPublicTtc: 73500 },
  { id: "r_c50", nom: "C50", prixUsineHt: 54574.10, prixPublicTtc: 75500 },
  { id: "r_c55", nom: "C55", prixUsineHt: 54574.10, prixPublicTtc: 75500 },
  { id: "r_c66ol", nom: "C66 Optimum Line", prixUsineHt: 59141.60, prixPublicTtc: 81800 },
  { id: "r_c86ol", nom: "C86 Optimum Line", prixUsineHt: 59141.60, prixPublicTtc: 81800 },
  { id: "r_606f", nom: "606F", prixUsineHt: 54864.10, prixPublicTtc: 75900 },
  { id: "r_666fol", nom: "666F Optimum Line", prixUsineHt: 60591.60, prixPublicTtc: 83800 },
  { id: "r_686f", nom: "686F", prixUsineHt: 55516.60, prixPublicTtc: 76800 },
  { id: "r_696fol", nom: "696F Optimum Line", prixUsineHt: 60591.60, prixPublicTtc: 83800 },
].map((v) => ({ ...v, marque: "Rapido", gamme: "Profilés (Séries C / 6F)", type: "CAMPING_CAR", collection: 2027 }));

const RAPIDO_INTEGRAUX_IDS = ["r_c55i", "r_c66iol", "r_c86iol", "r_850f", "r_866fol", "r_896fol", "r_8066dfalko", "r_8086dfalko", "r_8096dfalko", "r_i66mtruma", "r_i66malde", "r_i96mtruma", "r_i96malde", "r_i166malde", "r_i196malde"];

const RAPIDO_VEHICULES_INTEGRAUX = [
  { id: "r_c55i", nom: "C55I", prixUsineHt: 61389.10, prixPublicTtc: 84900 },
  { id: "r_c66iol", nom: "C66I Optimum Line", prixUsineHt: 66464.10, prixPublicTtc: 91900 },
  { id: "r_c86iol", nom: "C86I Optimum Line", prixUsineHt: 66464.10, prixPublicTtc: 91900 },
  { id: "r_850f", nom: "850F", prixUsineHt: 62114.10, prixPublicTtc: 85900 },
  { id: "r_866fol", nom: "866F Optimum Line", prixUsineHt: 67914.10, prixPublicTtc: 93900 },
  { id: "r_896fol", nom: "896F Optimum Line", prixUsineHt: 67914.10, prixPublicTtc: 93900 },
  { id: "r_8086dfalko", nom: "8086dF AL-KO", prixUsineHt: 70524.10, prixPublicTtc: 97500 },
  { id: "r_8066dfalko", nom: "8066dF AL-KO", prixUsineHt: 71974.10, prixPublicTtc: 99500 },
  { id: "r_8096dfalko", nom: "8096dF AL-KO", prixUsineHt: 71974.10, prixPublicTtc: 99500 },
  { id: "r_i66mtruma", nom: "I66M TRUMA (Mercedes)", prixUsineHt: 99391.47, prixPublicTtc: 138900 },
  { id: "r_i96mtruma", nom: "I96M TRUMA (Mercedes)", prixUsineHt: 99391.47, prixPublicTtc: 138900 },
  { id: "r_i66malde", nom: "I66M ALDE (Mercedes)", prixUsineHt: 102258.13, prixPublicTtc: 142900 },
  { id: "r_i96malde", nom: "I96M ALDE (Mercedes)", prixUsineHt: 102258.13, prixPublicTtc: 142900 },
  { id: "r_i166malde", nom: "I166M ALDE (Mercedes)", prixUsineHt: 115158.13, prixPublicTtc: 160900 },
  { id: "r_i196malde", nom: "I196M ALDE (Mercedes)", prixUsineHt: 115158.13, prixPublicTtc: 160900 },
].map((v) => ({ ...v, marque: "Rapido", gamme: "Intégraux (Séries C / 8F / 80dF / Distinction)", type: "CAMPING_CAR", collection: 2027 }));

const RAPIDO_VANS_IDS = ["r_v55ol", "r_v62ol", "r_v64", "r_v65xl", "r_v68"];

const RAPIDO_VEHICULES_VANS = [
  { id: "r_v55ol", nom: "V55 Optimum Line", prixUsineHt: 52553.40, prixPublicTtc: 71900 },
  { id: "r_v68", nom: "V68", prixUsineHt: 48886.73, prixPublicTtc: 66900 },
  { id: "r_v62ol", nom: "V62 Optimum Line", prixUsineHt: 54020.07, prixPublicTtc: 73900 },
  { id: "r_v64", nom: "V64", prixUsineHt: 50353.40, prixPublicTtc: 68900 },
  { id: "r_v65xl", nom: "V65 XL", prixUsineHt: 51086.73, prixPublicTtc: 69900 },
].map((v) => ({ ...v, marque: "Rapido", gamme: "Vans (Fourgons)", type: "CAMPING_CAR", collection: 2027 }));

// Source : Tarifs_HT_Camping-cars.pdf / Tarifs_public_Camping-cars.pdf — Adria, collection 2027 (tarif au 01/07/2026)
const ADRIA_VEHICULES_CC = [
  { id: "adria_compact_dc_citroen", nom: "Profilé COMPACT DC (Citroën Jumper Select)", prixUsineHt: 53763, prixPublicTtc: 75900 },
  { id: "adria_compact_dl_citroen", nom: "Profilé COMPACT DL (Citroën Jumper Select)", prixUsineHt: 53054, prixPublicTtc: 74900 },
  { id: "adria_compact_dl_fiat_supreme", nom: "Profilé COMPACT DL (Fiat Ducato Supreme)", prixUsineHt: 59429, prixPublicTtc: 83900 },
  { id: "adria_matrix_650dl_citroen", nom: "Profilé MATRIX 650 DL (Citroën Jumper Select)", prixUsineHt: 55604, prixPublicTtc: 78500 },
  { id: "adria_matrix_670dc_citroen", nom: "Profilé MATRIX 670 DC (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_matrix_670dl_citroen", nom: "Profilé MATRIX 670 DL (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_matrix_670dc_fiat_supreme", nom: "Profilé MATRIX 670 DC (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_matrix_670dl_fiat_supreme", nom: "Profilé MATRIX 670 DL (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_coral_670dc_citroen", nom: "Profilé CORAL 670 DC (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_coral_670dl_citroen", nom: "Profilé CORAL 670 DL (Citroën Jumper Select)", prixUsineHt: 56596, prixPublicTtc: 79900 },
  { id: "adria_coral_670dc_fiat_supreme", nom: "Profilé CORAL 670 DC (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_coral_670dl_fiat_supreme", nom: "Profilé CORAL 670 DL (Fiat Ducato Supreme)", prixUsineHt: 67221, prixPublicTtc: 94900 },
  { id: "adria_coralxl_650dk_citroen", nom: "Capucine CORAL XL 650 DK (Citroën Jumper Select)", prixUsineHt: 55179, prixPublicTtc: 77900 },
  { id: "adria_coralxl_660sl_citroen", nom: "Capucine CORAL XL 660 SL (Citroën Jumper Select)", prixUsineHt: 55888, prixPublicTtc: 78900 },
  { id: "adria_sonic_700dc_fiat_select", nom: "Intégral SONIC 700 DC (Fiat Ducato Select, 140cv MAN.)", prixUsineHt: 70472, prixPublicTtc: 99490 },
  { id: "adria_sonic_700dl_fiat_select", nom: "Intégral SONIC 700 DL (Fiat Ducato Select, 140cv MAN.)", prixUsineHt: 70472, prixPublicTtc: 99490 },
  { id: "adria_sonic_700dl_fiat_supreme", nom: "Intégral SONIC 700 DL (Fiat Ducato Supreme, 44H 160cv AUT.)", prixUsineHt: 82096, prixPublicTtc: 115900 },
  { id: "adria_sonic_700dc_fiat_supreme", nom: "Intégral SONIC 700 DC (Fiat Ducato Supreme, 44H 160cv AUT.)", prixUsineHt: 82096, prixPublicTtc: 115900 },
  { id: "adria_supersonic_780dc", nom: "Intégral SUPERSONIC 780 DC (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 116804, prixPublicTtc: 164900 },
  { id: "adria_supersonic_780dl", nom: "Intégral SUPERSONIC 780 DL (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 116804, prixPublicTtc: 164900 },
  { id: "adria_supersonic_780sl", nom: "Intégral SUPERSONIC 780 SL (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 116804, prixPublicTtc: 164900 },
  { id: "adria_supersonic_890lc", nom: "Intégral SUPERSONIC 890 LC (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 124596, prixPublicTtc: 175900 },
  { id: "adria_supersonic_890ll", nom: "Intégral SUPERSONIC 890 LL (Mercedes Benz 44H 170cv AUT.)", prixUsineHt: 124596, prixPublicTtc: 175900 },
].map((v) => ({ ...v, marque: "Adria", gamme: "Camping-cars", type: "CAMPING_CAR", collection: 2027 }));

// Source : Tarifs_HT_Fourgons.pdf / Tarifs_public_Fourgons.pdf — Adria, collection 2027 (tarif au 01/07/2026)
const ADRIA_VEHICULES_FOURGONS = [
  { id: "adria_twin_540spb_citroen", nom: "TWIN 540 SPB — Gamme Select (Citroën Jumper, 35L 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 43846, prixPublicTtc: 61900 },
  { id: "adria_twin_600spb_citroen_ptr", nom: "TWIN 600 SPB PTR — Gamme Select (Citroën Jumper, 35L 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 45263, prixPublicTtc: 63900 },
  { id: "adria_twin_600spb_family_citroen", nom: "TWIN 600 SPB FAMILY — Gamme Select (Citroën Jumper, 35L 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 45971, prixPublicTtc: 64900 },
  { id: "adria_twin_640slb_citroen_ptr", nom: "TWIN 640 SLB PTR — Gamme Select (Citroën Jumper, 35H 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 46679, prixPublicTtc: 65900 },
  { id: "adria_twin_640sgx_citroen_ptr", nom: "TWIN 640 SGX PTR — Gamme Select (Citroën Jumper, 35H 140cv MAN.)", gammeTwin: "Select", prixUsineHt: 48804, prixPublicTtc: 68900 },
  { id: "adria_twin_540spb_fiat_supreme_ptr", nom: "TWIN 540 SPB PTR — Gamme Supreme (Fiat Ducato, 35L 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 53763, prixPublicTtc: 75900 },
  { id: "adria_twin_600spb_fiat_supreme_ptr", nom: "TWIN 600 SPB PTR — Gamme Supreme (Fiat Ducato, 35L 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 50929, prixPublicTtc: 71900 },
  { id: "adria_twin_640spb_family_fiat_supreme", nom: "TWIN 640 SPB FAMILY — Gamme Supreme (Fiat Ducato, 35H 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 52346, prixPublicTtc: 73900 },
  { id: "adria_twin_640slb_fiat_supreme_ptr", nom: "TWIN 640 SLB PTR — Gamme Supreme (Fiat Ducato, 35H 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 52346, prixPublicTtc: 73900 },
  { id: "adria_twin_640sgx_fiat_supreme_ptr", nom: "TWIN 640 SGX PTR — Gamme Supreme (Fiat Ducato, 35H 140cv MAN.)", gammeTwin: "Supreme", prixUsineHt: 54471, prixPublicTtc: 76900 },
  { id: "adria_supertwin_600spb_ptr", nom: "SUPERTWIN 600 SPB PTR — Gamme Supertwin (Mercedes, 4X4 190cv AUT.)", gammeTwin: "Supertwin", prixUsineHt: 105471, prixPublicTtc: 148900 },
  { id: "adria_supertwin_700sgx_ptr", nom: "SUPERTWIN 700 SGX PTR — Gamme Supertwin (Mercedes, 4X4 190cv AUT.)", gammeTwin: "Supertwin", prixUsineHt: 110471, prixPublicTtc: 155900 },
].map((v) => ({ ...v, marque: "Adria", gamme: `Fourgons — ${v.gammeTwin}`, type: "CAMPING_CAR", collection: 2027 }));


const VEHICULES = [...DREAMER_VEHICULES, ...RAPIDO_VEHICULES, ...RAPIDO_VEHICULES_INTEGRAUX, ...RAPIDO_VEHICULES_VANS, ...ADRIA_VEHICULES_CC, ...ADRIA_VEHICULES_FOURGONS];

// ---------------------------------------------------------------------------
// OPTIONS (statut par véhicule : "O" option payante, "S" de série, "-"/absent indisponible)
// ---------------------------------------------------------------------------

const DREAMER_OPTIONS = [
  { id: "isolation_portes", nom: "Kit isolation portes arrière Grand Froid", achatHt: 191, cessionPose: 0, prixTtc: 270, poids: 2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "reservoir_chauffe", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 12,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "douchette", nom: "Douchette extérieure eau froide", achatHt: 135, cessionPose: 0, prixTtc: 190, poids: 1,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","S","S"]) },
  { id: "jantes", nom: "Jantes Stellantis alliage 16\"", achatHt: 600, cessionPose: 0, prixTtc: 800, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","O","S"]) },
  { id: "batterie_agm", nom: "2e batterie cellule AGM 95Ah", achatHt: 248, cessionPose: 0, prixTtc: 350, poids: 27,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","O","S"]) },
  { id: "moquette", nom: "Moquette cellule", achatHt: 390, cessionPose: 0, prixTtc: 550, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "toit_pano", nom: "Toit panoramique Skyview", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 20,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","-","O","-","O","-","O","-","O","-","-","-","O"]) },
  { id: "peinture_up", nom: "Peinture carrosserie gamme UP (Gris Artense / Storm Blue...)", achatHt: 1425, cessionPose: 0, prixTtc: 1900, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","O","O","-","-","O","O","-","-","O","O","-","-","-","-"]) },
  { id: "peinture_h2", nom: "Peinture carrosserie gamme H2", achatHt: 788, cessionPose: 0, prixTtc: 1050, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","-","-","O","O","-","-","O","O","-","-","-","-","-","-"]) },
  { id: "isolation_toile", nom: "Kit isolation toile de toit", achatHt: 584, cessionPose: 0, prixTtc: 820, poids: 4.6,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","O","O","-","-","O","O","-","-","O","O","-","-","-","-"]) },
  { id: "four", nom: "Four 20 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","O","O","O","O","O","O","O","O","O","-","-"]) },
  { id: "couchage_appoint", nom: "Couchage d'appoint 1 place", achatHt: 248, cessionPose: 0, prixTtc: 350, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","-","-","O","S","-","-","O","S","-","-","-","-","O","S"]) },
  { id: "kit_protection_matelas_d", nom: "Kit protection matelas", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 2.2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "kit_moquette_cabine_d", nom: "Kit moquette cabine", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "kit_lino_protecteur_d", nom: "Kit lino protecteur", achatHt: 140, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_arizona_d", nom: "Sellerie TEP Arizona", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","S","O","S","O","S","O","S","O","S","O","S","O","S","O","S"]) },
  { id: "bvm_140_35t_hd_vs120_d", nom: "FIAT/Peugeot 140ch BVM 3,5T Heavy Duty (vs 120ch BVM 3,5T)", achatHt: 1500, cessionPose: 0, prixTtc: 2000, poids: 0,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "bva_140_35t_ld_vs120_d", nom: "FIAT/Peugeot 140ch BVA 3,5T Light Duty (vs 120ch BVM 3,5T)", achatHt: 3938, cessionPose: 0, prixTtc: 5250, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "bva_140_35t_ld_vs140_d", nom: "FIAT/Peugeot 140ch BVA 3,5T Light Duty (vs 140ch BVM 3,5T)", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "bva_140_425t_hd_vs140_d", nom: "FIAT/Peugeot 140ch BVA 4,25T Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 3413, cessionPose: 0, prixTtc: 4550, poids: 45,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","-","-","-","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "bva_160_35t_hd_vs120_d", nom: "FIAT/Peugeot 160ch BVA 3,5T Heavy Duty (vs 120ch BVM 3,5T)", achatHt: 5100, cessionPose: 0, prixTtc: 6800, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["O","-","O","-","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "bva_160_35t_hd_vs140_d", nom: "FIAT/Peugeot 160ch BVA 3,5T Heavy Duty (vs 140ch BVM 3,5T)", achatHt: 3600, cessionPose: 0, prixTtc: 4800, poids: 5,
    compat: zipCompat(DREAMER_VEHICULE_IDS, ["-","O","-","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
].map((o) => ({ ...o, marque: "Dreamer" }));

const RAPIDO_OPTIONS = [
  { id: "toit_pano_r", nom: "Toit panoramique Skyview", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 20,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["S","S","S","S","S","-","-","-","-"]) },
  { id: "truma_combi", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique)", achatHt: 531, cessionPose: 0, prixTtc: 750, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "alde_confort", nom: "Chauffage central ALDE Confort Plus Arctic", achatHt: 3152, cessionPose: 0, prixTtc: 4450, poids: 65,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","O","-","-"]) },
  { id: "plancher_chauffant_r", nom: "Plancher chauffant cellule 230V", achatHt: 460, cessionPose: 0, prixTtc: 650, poids: 7,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "reservoir_chauffe_r", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 15,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_palma", nom: "Sellerie TEP Palma (mobilier Palatina)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","S","S","S","S"]) },
  { id: "lit_pavillon", nom: "Lit de pavillon relevable électriquement (2 pers.)", achatHt: 1488, cessionPose: 0, prixTtc: 2100, poids: 45,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","O","O","O"]) },
  { id: "four23", nom: "Four 23 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 22,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","-","O","O","O"]) },
  { id: "lit_bas_reglable", nom: "Lit permanent bas réglable en hauteur (vérins électriques)", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","O","-","-","O","-","O","O","O"]) },
  { id: "batterie_2e", nom: "2e batterie cellule LITHIUM 150Ah", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","O","O","O","O","O","O","O","O"]) },
  { id: "convertisseur", nom: "Convertisseur 2000W avec coupe batterie", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","S","S","-","S","-","S"]) },
  { id: "bva_fiat_peugeot", nom: "Boîte de vitesses automatique Fiat/Peugeot", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","O","S","O","S"]) },
  { id: "moquette_chauffante_alde_r", nom: "Moquette chauffante ALDE cabine (oblige chauffage ALDE)", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 6,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","-","O","-","-"]) },
  { id: "sellerie_milan_r", nom: "Sellerie TEP Milan", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_noumea_r", nom: "Sellerie TEP Noumea (mobilier Aurora)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","S","S","S","S"]) },
  { id: "sellerie_alba_r", nom: "Sellerie Tissu Alba", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "four22_r", nom: "Four 22 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","-","-","O","-","-","-"]) },
  { id: "surmatelas_r", nom: "Sur-matelas à mémoire de forme sur lit permanent", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 6,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","-","-","O","-","-","O","O"]) },
  { id: "kit_lino_r", nom: "Kit lino protecteur", achatHt: 140, cessionPose: 0, prixTtc: 200, poids: 2,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "douchette_r", nom: "Douchette extérieure eau chaude/froide", achatHt: 142, cessionPose: 0, prixTtc: 200, poids: 1,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "fiat_160ch_r", nom: "FIAT/Peugeot 160 ch (vs 140 ch)", achatHt: 1163, cessionPose: 0, prixTtc: 1550, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "attelage_r", nom: "Attelage 2000 kg maxi (sous réserve PTRA)", achatHt: 1063, cessionPose: 0, prixTtc: 1420, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "led_r", nom: "Projecteurs avant 100% LED", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "retro_double_vision_r", nom: "Rétroviseurs extérieurs double vision", achatHt: 213, cessionPose: 0, prixTtc: 280, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["S","S","S","S","S","S","S","S","S"]) },
  { id: "retro_rabattables_r", nom: "Rétroviseurs extérieurs rabattables électriquement", achatHt: 263, cessionPose: 0, prixTtc: 350, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","-","-","-","-"]) },
  { id: "verins_stabilisation_r", nom: "Vérins de stabilisation", achatHt: 128, cessionPose: 0, prixTtc: 180, poids: 5,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_energy_r", nom: "PACK ENERGY (monté usine) : batterie Lithium + panneau solaire 150W", achatHt: 758, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","O","S","O","S"]) },
  { id: "pack_smart_r", nom: "PACK SMART : jantes 16'' bi-ton, volant confort, habillage aérateurs", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","S","S","O","S","O","S"]) },
  { id: "pack_lounge_r", nom: "PACK LOUNGE : climatisation cabine auto, chargeur induction, combiné digital", achatHt: 743, cessionPose: 0, prixTtc: 990, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_adapt_r", nom: "PACK ADAPT : régulateur adaptatif + capteur pluie/luminosité", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","O","O","O","O","O","O"]) },
  { id: "pack_keyless_full_r", nom: "PACK KEYLESS : accès/démarrage sans clé + frein de stationnement électrique", achatHt: 863, cessionPose: 0, prixTtc: 1150, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","-","-","O","-","O","-"]) },
  { id: "pack_keyless_basic_r", nom: "PACK KEYLESS : accès/démarrage sans clé", achatHt: 413, cessionPose: 0, prixTtc: 550, poids: 0,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","O","O","-","O","-","O"]) },
  { id: "nav_pioneer_a_r", nom: "Navigation multimédia DAB Pioneer 9\" (CarPlay/Android Auto)", achatHt: 744, cessionPose: 0, prixTtc: 1050, poids: 2,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["O","O","O","-","-","O","-","O","-"]) },
  { id: "nav_pioneer_b_r", nom: "Navigation multimédia DAB Pioneer 9\" (CarPlay/Android Auto) — variante", achatHt: 425, cessionPose: 0, prixTtc: 600, poids: 2,
    compat: zipCompat(RAPIDO_VEHICULE_IDS, ["-","-","-","O","O","-","O","-","O"]) },
].map((o) => ({ ...o, marque: "Rapido" }));

const RAPIDO_OPTIONS_INTEGRAUX = [
  { id: "pack_energy_i", nom: "PACK ENERGY (batterie Lithium + panneau solaire 150W)", achatHt: 758, cessionPose: 0, prixTtc: 1500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","-","-","-","-","-","-","-","-","-"]) },
  { id: "pack_smart_i", nom: "PACK SMART (jantes 16'' bi-ton, volant confort)", achatHt: 825, cessionPose: 0, prixTtc: 1100, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","-","-","-","-","-","-"]) },
  { id: "pack_lounge_i", nom: "PACK LOUNGE (climatisation auto + chargeur induction)", achatHt: 743, cessionPose: 0, prixTtc: 990, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "pack_drive_assist_66_96", nom: "PACK DRIVE ASSIST i66M/i96M", achatHt: 3075, cessionPose: 0, prixTtc: 4100, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","O","O","O","-","-"]) },
  { id: "pack_drive_assist_166_196", nom: "PACK DRIVE ASSIST i166M/i196M", achatHt: 2175, cessionPose: 0, prixTtc: 2900, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","O","O"]) },
  { id: "bva_fiat_i", nom: "Boîte de vitesses automatique FIAT", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","-","-","-","-","-","-"]) },
  { id: "fiat_160ch_i", nom: "FIAT 160 ch (vs 140 ch)", achatHt: 1163, cessionPose: 0, prixTtc: 1550, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "chassis_heavy", nom: "Châssis HEAVY : PTAC 4,5T (réservoir 93L inclus)", achatHt: 1875, cessionPose: 0, prixTtc: 2500, poids: 40,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","S","O","S","S","S"]) },
  { id: "frein_stationnement_i", nom: "Frein de stationnement électrique", achatHt: 450, cessionPose: 0, prixTtc: 600, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","-","-","-","S","S","S","S","S","S"]) },
  { id: "led_i", nom: "Projecteurs avant 100% LED", achatHt: 921, cessionPose: 0, prixTtc: 1300, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","S","S"]) },
  { id: "retro_double_vision", nom: "Rétroviseurs extérieurs double vision", achatHt: 213, cessionPose: 0, prixTtc: 280, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","S","S","S","S","S","S"]) },
  { id: "verins_stabilisation", nom: "Vérins de stabilisation", achatHt: 128, cessionPose: 0, prixTtc: 180, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","S","O","S","S","S"]) },
  { id: "truma_combi_a_i", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique) — gamme C/8F", achatHt: 531, cessionPose: 0, prixTtc: 750, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "truma_combi_b_i", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique) — 850F/866F OL/896F OL", achatHt: 446, cessionPose: 0, prixTtc: 630, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "truma_combi_c_i", nom: "TRUMA Combi 6 EH (gaz + électrique) — gamme 80dF", achatHt: 390, cessionPose: 0, prixTtc: 550, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "alde_confort_i", nom: "Chauffage central ALDE Confort Plus Arctic", achatHt: 3542, cessionPose: 0, prixTtc: 5000, poids: 65,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","-","O","-","-","-","-","-","-"]) },
  { id: "plancher_chauffant_i", nom: "Plancher chauffant cellule 230V", achatHt: 460, cessionPose: 0, prixTtc: 650, poids: 7,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "plancher_chauffant_alde_i", nom: "Plancher chauffant cellule ALDE à eau chaude", achatHt: 460, cessionPose: 0, prixTtc: 650, poids: 8,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","-","O","-","O","-","O","O","O"]) },
  { id: "moquette_chauffante_alde_i", nom: "Moquette chauffante ALDE cabine", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 6,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","-","O","-","O","-","O","O","O"]) },
  { id: "reservoir_chauffe_i", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 15,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","S","S","S","S","S","S","S","S","S","S","S"]) },
  { id: "clim_cellule_truma_i", nom: "Climatisation cellule TRUMA 2500W (monté usine)", achatHt: 1417, cessionPose: 0, prixTtc: 2000, poids: 45,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","-","-","-","-","O","O"]) },
  { id: "tiroir_rangement_i", nom: "Tiroir de rangement extérieur coulissant (45L / 25kg)", achatHt: 496, cessionPose: 0, prixTtc: 700, poids: 18,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","O","O","-","-","-","-","-","-","-","-","-"]) },
  { id: "sellerie_milan_i", nom: "Sellerie TEP Milan", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "sellerie_cuir_austin_i", nom: "Sellerie cuir Austin", achatHt: 1771, cessionPose: 0, prixTtc: 2500, poids: 8,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_cuir_braga_i", nom: "Sellerie cuir Braga", achatHt: 1771, cessionPose: 0, prixTtc: 2500, poids: 8,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_palma_i", nom: "Sellerie TEP Palma (mobilier Palatina)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","S","S","S","S","S","S"]) },
  { id: "sellerie_noumea_i", nom: "Sellerie TEP Noumea (mobilier Aurora)", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","S","S","O","S","S","S","S","S","S","S","S","S","S","S"]) },
  { id: "sellerie_budapest_i", nom: "Sellerie Tissu Budapest", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 5,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","O","O","O","O","O","O"]) },
  { id: "sellerie_alba_i", nom: "Sellerie Tissu Alba", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"]) },
  { id: "refrigerateur_compression_i", nom: "Réfrigérateur à compression", achatHt: 354, cessionPose: 0, prixTtc: 500, poids: 0,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","O","O","O","-","-","-","-","-","-"]) },
  { id: "four23_i", nom: "Four 23 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 22,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["O","O","O","O","O","O","O","O","O","-","-","-","-","-","-"]) },
  { id: "tectower_i", nom: "TEC-Tower : combiné réfrigérateur et four 25L avec grill", achatHt: 885, cessionPose: 0, prixTtc: 1250, poids: 21,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","-","-","-","-","-","-","O","O","O","O","S","S"]) },
  { id: "lit_bas_30cm_i", nom: "Lit permanent bas réglable (~30cm) vérins électriques", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","-","O","-","O","-","O","O","-","-","S","S","-","S"]) },
  { id: "lit_bas_20cm_i", nom: "Lit permanent bas réglable (~20cm) vérins électriques", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","O","-","-","-","-","-","-","-","-","-","-","-","-"]) },
  { id: "surmatelas_i", nom: "Sur-matelas à mémoire de forme sur lit permanent", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 6,
    compat: zipCompat(RAPIDO_INTEGRAUX_IDS, ["-","-","O","O","-","O","-","O","O","-","-","O","O","-","S"]) },
].map((o) => ({ ...o, marque: "Rapido" }));

const RAPIDO_OPTIONS_VANS = [
  { id: "toit_pano_van", nom: "Toit panoramique Skyview", achatHt: 1063, cessionPose: 0, prixTtc: 1500, poids: 20,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","-","O"]) },
  { id: "isolation_portes_van", nom: "Kit isolation portes arrière Grand Froid", achatHt: 191, cessionPose: 0, prixTtc: 270, poids: 2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "truma_combi_van", nom: "TRUMA Combi 6 EH Diesel (diesel + électrique)", achatHt: 531, cessionPose: 0, prixTtc: 750, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","-","O","O"]) },
  { id: "plancher_chauffant_van", nom: "Plancher chauffant cellule 230V", achatHt: 319, cessionPose: 0, prixTtc: 450, poids: 5,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "reservoir_chauffe_van", nom: "Réservoir d'eaux usées chauffé", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 12,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "sellerie_milan_van", nom: "Sellerie TEP Milan", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "four20_van", nom: "Four 20 litres avec grill", achatHt: 638, cessionPose: 0, prixTtc: 900, poids: 15,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","-","O","O","O"]) },
  { id: "surmatelas_van", nom: "Sur-matelas à mémoire de forme sur lit permanent", achatHt: 283, cessionPose: 0, prixTtc: 400, poids: 6,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","-"]) },
  { id: "kit_protection_matelas_van", nom: "Kit protection matelas", achatHt: 213, cessionPose: 0, prixTtc: 300, poids: 2.2,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "moquette_van", nom: "Moquette cellule", achatHt: 390, cessionPose: 0, prixTtc: 550, poids: 5,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "bva_van", nom: "Boîte de vitesses automatique Fiat/Peugeot", achatHt: 2438, cessionPose: 0, prixTtc: 3250, poids: 5,
    compat: zipCompat(RAPIDO_VANS_IDS, ["S","S","O","O","O"]) },
  { id: "fiat_160ch_van", nom: "FIAT/Peugeot 160 ch (vs 140 ch)", achatHt: 1163, cessionPose: 0, prixTtc: 1550, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
  { id: "led_van", nom: "Projecteurs avant 100% LED", achatHt: 750, cessionPose: 0, prixTtc: 1000, poids: 0,
    compat: zipCompat(RAPIDO_VANS_IDS, ["O","O","O","O","O"]) },
].map((o) => ({ ...o, marque: "Rapido" }));

const OPTIONS = [...DREAMER_OPTIONS, ...RAPIDO_OPTIONS, ...RAPIDO_OPTIONS_INTEGRAUX, ...RAPIDO_OPTIONS_VANS];

module.exports = { VEHICULES, OPTIONS };
